ftp:
  servers:
    - code: FGLS
      name: 辅助系统 FTP
      desc: 财务相关
      host: 198.19.249.12
      port: 21
      user: ftpuser
      password: songtaoxy
      passiveMode: false
      path: /files
    - code: NC
      name: NC 系统 FTP
      desc: 交换
      host: 10.0.0.20
      port: 21
      user: u2
      password: p2
      passiveMode: false
      path: a/b/c
