spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  mvc:
    # spring boot 2.6.5与Swagger3.0.0兼容问题. ref https://blog.csdn.net/hadues/article/details/123753888
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    #   数据源基本配置
#    username: root
#    password: songtaoxy
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springboot
#    type: com.alibaba.druid.pool.DruidDataSource
#    #   数据源其他配置
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,log4j
#    filters: stat,wall
#    maxPoolPreparedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#
  data:
    redis:
      client-type: lettuce
  redis:
    host: localhost
    port: 6379
    # Redis 6+ 启用 ACL 才需要 username；否则删掉该行
    username: default
    database: 0
    timeout: 2s
    ssl: false
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 0
        max-wait: 2s


#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql
mybatis:
  # 该配置(文件)可以不用.
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 取代config-location;configuration与config-location不能同时使用.
  configuration:
    mapUnderscoreToCamelCase: true

# 请求参数脱敏（支持配置规则）配置脱敏字段
log:
  sensitiveFields:
    - password
    - idCard
    - phone


# ================================
# 线程池配置 test1
# ================================
st:
  concurrent:
    biz:
      pool-name: biz-pool
      core: 8
      max: 32
      queue: 256
      bulkhead-permits: 0
      rate-limit-enabled: true
      rate-limit-qps: 300
      rate-burst: 600
      breaker-enabled: true
      breaker-failure-threshold: 5
      breaker-open-millis: 2000
      breaker-half-open-permits: 2
      shutdown-wait-seconds: 20

# ================================
# 线程池配置 test2
# ================================
best:
  concurrent:
    pool-name: biz
    core: 8
    max: 32
    queue: 256
    keep-alive-seconds: 60
    bulkhead-permits: 0
    rate-limit-enabled: true
    rate-limit-qps: 300
    rate-burst: 600
    breaker-enabled: true
    breaker-failure-threshold: 5
    breaker-open-millis: 2000
    breaker-half-open-permits: 2



# ---------------------
# 集成Prometheus Grafana
# Actuator + Micrometer 的管理与指标配置
# ---------------------
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true


ftp:
  clients:
    ftpA:
      protocol: ftp
      host: 192.168.1.100
      port: 21
      username: user
      password: pass
      paths:
        upload: /upload
        download: /download
    sftpB:
      protocol: sftp
      host: 192.168.1.101
      port: 22
      username: user2
      password: pass2
      paths:
        upload: /data/in
