package com.st.api.practice.gson;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.parser.Feature;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;

/**
 * @author: st
 * @date: 2021/7/15 10:49
 * @version: 1.0
 * @description:
 */
@Slf4j
public class GsonSort2JsonSort {

  public static String jsonStr =
      "{\n"
          + "\t\"model\": {\n"
          + "\t\t\"_id\": {\n"
          + "\t\t\t\"$oid\": \"60cb44860492b60059774cec\"\n"
          + "\t\t},\n"
          + "\t\t\"metaComponentId\": \"4d71ce1d-6211-4060-a19e-eeff9986a666\",\n"
          + "\t\t\"dataRelation\": \"Join\",\n"
          + "\t\t\"mul_language\": {\n"
          + "\t\t\t\"zh_CN\": {},\n"
          + "\t\t\t\"en_US\": {},\n"
          + "\t\t\t\"zh_TW\": {}\n"
          + "\t\t},\n"
          + "\t\t\"description\": \"关联查询-条件参数过滤\",\n"
          + "\t\t\"id\": \"7694c998-debc-4f16-94fd-d11385b0b328\",\n"
          + "\t\t\"modelType\": \"Report\",\n"
          + "\t\t\"metaType\": \"Class\",\n"
          + "\t\t\"name\": \"test019\",\n"
          + "\t\t\"displayName\": \"test019\",\n"
          + "\t\t\"uri\": \"GT69287AT56.report.test019\",\n"
          + "\t\t\"version\": 1,\n"
          + "\t\t\"tenantId\": \"edr19n2r\",\n"
          + "\t\t\"ytenant_id\": \"edr19n2r\",\n"
          + "\t\t\"metadataLevel\": \"2\",\n"
          + "\t\t\"domain\": \"report\",\n"
          + "\t\t\"status\": \"3\",\n"
          + "\t\t\"ownedAttribute\": [{\n"
          + "\t\t\t\"name\": \"modifier\",\n"
          + "\t\t\t\"fieldName\": \"modifier\",\n"
          + "\t\t\t\"displayName\": \"修改人\",\n"
          + "\t\t\t\"type\": \"String\",\n"
          + "\t\t\t\"length\": \"36\",\n"
          + "\t\t\t\"id\": \"126fa209-3b07-4135-88e8-4badb61d794b\",\n"
          + "\t\t\t\"uri\": \"bd.bank.BankTreeViewVO.modifier\",\n"
          + "\t\t\t\"parentUri\": \"bd.bank.BankTreeViewVO\",\n"
          + "\t\t\t\"nullable\": true,\n"
          + "\t\t\t\"terms\": [],\n"
          + "\t\t\t\"metaType\": \"Property\",\n"
          + "\t\t\t\"moelType\": \"EntityAttrModel\",\n"
          + "\t\t\t\"version\": 13,\n"
          + "\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\"id\": \"String\",\n"
          + "\t\t\t\t\"name\": \"字符型\",\n"
          + "\t\t\t\t\"uri\": \"String\",\n"
          + "\t\t\t\t\"metaType\": \"PrimitiveType\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"key\": false,\n"
          + "\t\t\t\"precise\": \"2\",\n"
          + "\t\t\t\"isKey\": false,\n"
          + "\t\t\t\"isNewDataName\": false,\n"
          + "\t\t\t\"isNewDataCode\": false,\n"
          + "\t\t\t\"is_mul_language\": false,\n"
          + "\t\t\t\"isUnique\": false,\n"
          + "\t\t\t\"_key\": \"126fa209-3b07-4135-88e8-4badb61d794b\",\n"
          + "\t\t\t\"categoriesString\": \"\",\n"
          + "\t\t\t\"mul_language_resid\": {\n"
          + "\t\t\t\t\"displayName\": \"P_YS_PF_GZTORG_0000035173\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"code\": \"modifier\",\n"
          + "\t\t\t\"metaClassId\": \"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\n"
          + "\t\t\t\"oriName\": \"modifier\"\n"
          + "\t\t}, {\n"
          + "\t\t\t\"fieldName\": \"dr\",\n"
          + "\t\t\t\"key\": false,\n"
          + "\t\t\t\"nullable\": false,\n"
          + "\t\t\t\"length\": \"1\",\n"
          + "\t\t\t\"precise\": \"2\",\n"
          + "\t\t\t\"uri\": \"basedoc.basedocentity.BasedocBizObject.dr\",\n"
          + "\t\t\t\"name\": \"dr\",\n"
          + "\t\t\t\"displayName\": \"逻辑删除标记\",\n"
          + "\t\t\t\"type\": \"Short\",\n"
          + "\t\t\t\"id\": \"83e2fc3e-57e0-4ee1-a5fe-86c3d323dc58\",\n"
          + "\t\t\t\"parentUri\": \"basedoc.basedocentity.BasedocBizObject\",\n"
          + "\t\t\t\"terms\": [{\n"
          + "\t\t\t\t\"_id\": {\n"
          + "\t\t\t\t\t\"$oid\": \"5cdfa460dd026f004e51d025\"\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"code\": \"DRFLAG\",\n"
          + "\t\t\t\t\"name\": \"删除标志\",\n"
          + "\t\t\t\t\"description\": \"\",\n"
          + "\t\t\t\t\"targetType\": \"PROPERTY\",\n"
          + "\t\t\t\t\"id\": \"dea521fb-2e9c-4d96-8461-949a9b8121fa\",\n"
          + "\t\t\t\t\"categories\": [{\n"
          + "\t\t\t\t\t\"code\": \"specialAttr\",\n"
          + "\t\t\t\t\t\"modifyTime\": \"2019-05-18 14:20:11:134\",\n"
          + "\t\t\t\t\t\"createTime\": \"2019-05-18 14:20:11:134\",\n"
          + "\t\t\t\t\t\"name\": \"特殊属性\",\n"
          + "\t\t\t\t\t\"description\": \"\",\n"
          + "\t\t\t\t\t\"_id\": {\n"
          + "\t\t\t\t\t\t\"$oid\": \"5cdfa41bdd026f004e51d023\"\n"
          + "\t\t\t\t\t},\n"
          + "\t\t\t\t\t\"id\": \"9979b678-6613-45e7-bcc0-fb4ce330df4b\",\n"
          + "\t\t\t\t\t\"parentId\": \"0\",\n"
          + "\t\t\t\t\t\"mul_language\": {\n"
          + "\t\t\t\t\t\t\"zh_TW\": {},\n"
          + "\t\t\t\t\t\t\"en_US\": {},\n"
          + "\t\t\t\t\t\t\"zh_CN\": {\n"
          + "\t\t\t\t\t\t\t\"name\": \"特殊属性\"\n"
          + "\t\t\t\t\t\t}\n"
          + "\t\t\t\t\t}\n"
          + "\t\t\t\t}],\n"
          + "\t\t\t\t\"mul_language\": {\n"
          + "\t\t\t\t\t\"zh_TW\": {},\n"
          + "\t\t\t\t\t\"en_US\": {},\n"
          + "\t\t\t\t\t\"zh_CN\": {\n"
          + "\t\t\t\t\t\t\"name\": \"删除标志\"\n"
          + "\t\t\t\t\t}\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"createTime\": \"2019-05-18 14:21:20:985\",\n"
          + "\t\t\t\t\"modifyTime\": \"2019-05-18 14:22:04:363\",\n"
          + "\t\t\t\t\"version\": 1\n"
          + "\t\t\t}],\n"
          + "\t\t\t\"metaType\": \"Property\",\n"
          + "\t\t\t\"modelType\": \"EntityAttrModel\",\n"
          + "\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\"id\": \"Short\",\n"
          + "\t\t\t\t\"name\": \"短整数\",\n"
          + "\t\t\t\t\"uri\": \"Short\",\n"
          + "\t\t\t\t\"metaType\": \"PrimitiveType\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"version\": 12,\n"
          + "\t\t\t\"defaultValue\": \"0\",\n"
          + "\t\t\t\"isKey\": false,\n"
          + "\t\t\t\"isNewDataName\": false,\n"
          + "\t\t\t\"isNewDataCode\": false,\n"
          + "\t\t\t\"_key\": \"83e2fc3e-57e0-4ee1-a5fe-86c3d323dc58\",\n"
          + "\t\t\t\"categoriesString\": \"删除标志\",\n"
          + "\t\t\t\"mul_language_resid\": {\n"
          + "\t\t\t\t\"displayName\": \"P_YS_PF_GZTTMP_0000073434\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"code\": \"dr\",\n"
          + "\t\t\t\"metaClassId\": \"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\n"
          + "\t\t\t\"oriName\": \"dr\"\n"
          + "\t\t}, {\n"
          + "\t\t\t\"name\": \"code\",\n"
          + "\t\t\t\"fieldName\": \"code\",\n"
          + "\t\t\t\"displayName\": \"编码\",\n"
          + "\t\t\t\"type\": \"String\",\n"
          + "\t\t\t\"length\": \"100\",\n"
          + "\t\t\t\"id\": \"71f1489e-9182-4301-b41d-2bc33be896be\",\n"
          + "\t\t\t\"uri\": \"bd.bank.BankDotVO.code\",\n"
          + "\t\t\t\"parentUri\": \"bd.bank.BankDotVO\",\n"
          + "\t\t\t\"nullable\": false,\n"
          + "\t\t\t\"terms\": [{\n"
          + "\t\t\t\t\"_id\": {\n"
          + "\t\t\t\t\t\"$oid\": \"5d67abd803ff9c0060a9d3d0\"\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"code\": \"isCode\",\n"
          + "\t\t\t\t\"name\": \"单据号\",\n"
          + "\t\t\t\t\"description\": \"isCode\",\n"
          + "\t\t\t\t\"targetType\": \"\",\n"
          + "\t\t\t\t\"id\": \"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\n"
          + "\t\t\t\t\"categories\": [{\n"
          + "\t\t\t\t\t\"code\": \"flow\",\n"
          + "\t\t\t\t\t\"modifyTime\": \"2020-06-13 14:47:44:975\",\n"
          + "\t\t\t\t\t\"createTime\": \"2020-06-13 14:47:44:975\",\n"
          + "\t\t\t\t\t\"name\": \"流程\",\n"
          + "\t\t\t\t\t\"description\": \"\",\n"
          + "\t\t\t\t\t\"_id\": {\n"
          + "\t\t\t\t\t\t\"$oid\": \"5ee476902c5df9005fdd5ad4\"\n"
          + "\t\t\t\t\t},\n"
          + "\t\t\t\t\t\"id\": \"0f8c698f-d881-4a73-be89-5a95ee5ba391\",\n"
          + "\t\t\t\t\t\"parentId\": \"0\",\n"
          + "\t\t\t\t\t\"mul_language\": {\n"
          + "\t\t\t\t\t\t\"zh_TW\": {},\n"
          + "\t\t\t\t\t\t\"en_US\": {},\n"
          + "\t\t\t\t\t\t\"zh_CN\": {\n"
          + "\t\t\t\t\t\t\t\"name\": \"流程\"\n"
          + "\t\t\t\t\t\t}\n"
          + "\t\t\t\t\t}\n"
          + "\t\t\t\t}],\n"
          + "\t\t\t\t\"mul_language\": {\n"
          + "\t\t\t\t\t\"zh_TW\": {},\n"
          + "\t\t\t\t\t\"en_US\": {},\n"
          + "\t\t\t\t\t\"zh_CN\": {\n"
          + "\t\t\t\t\t\t\"name\": \"单据号\"\n"
          + "\t\t\t\t\t}\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"createTime\": \"2019-08-29 18:41:28:693\",\n"
          + "\t\t\t\t\"modifyTime\": \"2020-06-13 14:48:23:468\",\n"
          + "\t\t\t\t\"version\": 2,\n"
          + "\t\t\t\t\"xmlTag\": \"isCode\",\n"
          + "\t\t\t\t\"refpk\": \"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\n"
          + "\t\t\t\t\"key\": \"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\n"
          + "\t\t\t\t\"refcode\": \"isCode\",\n"
          + "\t\t\t\t\"refname\": \"单据号\",\n"
          + "\t\t\t\t\"memo\": \"isCode\"\n"
          + "\t\t\t}],\n"
          + "\t\t\t\"metaType\": \"Property\",\n"
          + "\t\t\t\"modelType\": \"EntityAttrModel\",\n"
          + "\t\t\t\"version\": 21,\n"
          + "\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\"id\": \"String\",\n"
          + "\t\t\t\t\"name\": \"字符型\",\n"
          + "\t\t\t\t\"uri\": \"String\",\n"
          + "\t\t\t\t\"metaType\": \"PrimitiveType\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"isKey\": false,\n"
          + "\t\t\t\"precise\": \"2\",\n"
          + "\t\t\t\"isUnique\": true,\n"
          + "\t\t\t\"isRequired\": true,\n"
          + "\t\t\t\"createTime\": \"2019-09-04 17:30:52:458\",\n"
          + "\t\t\t\"modifyTime\": \"2019-09-04 17:30:52:458\",\n"
          + "\t\t\t\"_key\": \"71f1489e-9182-4301-b41d-2bc33be896be\",\n"
          + "\t\t\t\"isNewDataName\": false,\n"
          + "\t\t\t\"isNewDataCode\": false,\n"
          + "\t\t\t\"is_mul_language\": false,\n"
          + "\t\t\t\"mul_language_resid\": {\n"
          + "\t\t\t\t\"displayName\": \"P_YS_FED_EXAMP_0000020286\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"categoriesString\": \"单据号\",\n"
          + "\t\t\t\"key\": false,\n"
          + "\t\t\t\"isCode\": true,\n"
          + "\t\t\t\"code\": \"code\",\n"
          + "\t\t\t\"metaClassId\": \"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\n"
          + "\t\t\t\"oriName\": \"code\"\n"
          + "\t\t}, {\n"
          + "\t\t\t\"displayName\": \"多语资源id\",\n"
          + "\t\t\t\"name\": \"name_resid\",\n"
          + "\t\t\t\"fieldName\": \"name_resid\",\n"
          + "\t\t\t\"id\": \"b5ed8731-718f-40d7-981e-c78e6e7ba145\",\n"
          + "\t\t\t\"isNewDataName\": false,\n"
          + "\t\t\t\"isNewDataCode\": false,\n"
          + "\t\t\t\"nullable\": \"true\",\n"
          + "\t\t\t\"length\": 256,\n"
          + "\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\"name\": \"字符型\",\n"
          + "\t\t\t\t\"id\": \"String\",\n"
          + "\t\t\t\t\"metaType\": \"PrimitiveType\",\n"
          + "\t\t\t\t\"uri\": \"String\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"precise\": \"2\",\n"
          + "\t\t\t\"uri\": \"bd.bank.BankDotVO.name_resid\",\n"
          + "\t\t\t\"tenantId\": \"sys\",\n"
          + "\t\t\t\"metadataLevel\": \"0\",\n"
          + "\t\t\t\"modelType\": \"EntityAttrModel\",\n"
          + "\t\t\t\"metaType\": \"Property\",\n"
          + "\t\t\t\"version\": 4,\n"
          + "\t\t\t\"createTime\": \"2020-05-13 09:48:17:067\",\n"
          + "\t\t\t\"modifyTime\": \"2020-05-13 09:48:17:067\",\n"
          + "\t\t\t\"terms\": [],\n"
          + "\t\t\t\"_key\": \"b5ed8731-718f-40d7-981e-c78e6e7ba145\",\n"
          + "\t\t\t\"categoriesString\": \"\",\n"
          + "\t\t\t\"mul_language_resid\": {\n"
          + "\t\t\t\t\"displayName\": \"P_YS_PF_METADATA_0001077410\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"is_mul_language\": false,\n"
          + "\t\t\t\"code\": \"name_resid\",\n"
          + "\t\t\t\"metaClassId\": \"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\n"
          + "\t\t\t\"oriName\": \"name_resid\"\n"
          + "\t\t}, {\n"
          + "\t\t\t\"name\": \"bank\",\n"
          + "\t\t\t\"fieldName\": \"bank\",\n"
          + "\t\t\t\"displayName\": \"社会级银行类别\",\n"
          + "\t\t\t\"type\": \"String\",\n"
          + "\t\t\t\"length\": \"36\",\n"
          + "\t\t\t\"id\": \"276d84cb-245b-4db4-ad6d-b6498abe9f41\",\n"
          + "\t\t\t\"uri\": \"bd.bank.BankTreeViewVO.bank\",\n"
          + "\t\t\t\"parentUri\": \"bd.bank.BankTreeViewVO\",\n"
          + "\t\t\t\"nullable\": true,\n"
          + "\t\t\t\"terms\": [],\n"
          + "\t\t\t\"metaType\": \"Property\",\n"
          + "\t\t\t\"modelType\": \"EntityAttrModel\",\n"
          + "\t\t\t\"version\": 3,\n"
          + "\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\"id\": \"String\",\n"
          + "\t\t\t\t\"name\": \"字符型\",\n"
          + "\t\t\t\t\"uri\": \"String\",\n"
          + "\t\t\t\t\"metaType\": \"PrimitiveType\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"key\": false,\n"
          + "\t\t\t\"precise\": \"2\",\n"
          + "\t\t\t\"isKey\": false,\n"
          + "\t\t\t\"isNewDataName\": false,\n"
          + "\t\t\t\"isNewDataCode\": false,\n"
          + "\t\t\t\"is_mul_language\": false,\n"
          + "\t\t\t\"isUnique\": false,\n"
          + "\t\t\t\"_key\": \"276d84cb-245b-4db4-ad6d-b6498abe9f41\",\n"
          + "\t\t\t\"categoriesString\": \"\",\n"
          + "\t\t\t\"mul_language_resid\": {\n"
          + "\t\t\t\t\"displayName\": \"P_YS_PF_METADATA_0000084990\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"serialNumber\": 210,\n"
          + "\t\t\t\"code\": \"bank\",\n"
          + "\t\t\t\"metaClassId\": \"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\n"
          + "\t\t\t\"oriName\": \"bank\"\n"
          + "\t\t}],\n"
          + "\t\t\"createTime\": \"2021-06-21 10:24:42:927\",\n"
          + "\t\t\"modifyTime\": \"2021-06-21 10:24:42:927\",\n"
          + "\t\t\"oriFields\": [{\n"
          + "\t\t\t\"name\": \"modifier\",\n"
          + "\t\t\t\"tableCode\": \"BankTreeViewVO\",\n"
          + "\t\t\t\"code\": \"modifier\",\n"
          + "\t\t\t\"dataType\": \"String\"\n"
          + "\t\t}, {\n"
          + "\t\t\t\"name\": \"dr\",\n"
          + "\t\t\t\"tableCode\": \"BankTreeViewVO\",\n"
          + "\t\t\t\"code\": \"dr\",\n"
          + "\t\t\t\"dataType\": \"Short\"\n"
          + "\t\t}, {\n"
          + "\t\t\t\"name\": \"code\",\n"
          + "\t\t\t\"tableCode\": \"BankDotVO\",\n"
          + "\t\t\t\"code\": \"code\",\n"
          + "\t\t\t\"dataType\": \"String\"\n"
          + "\t\t}, {\n"
          + "\t\t\t\"name\": \"name_resid\",\n"
          + "\t\t\t\"tableCode\": \"BankDotVO\",\n"
          + "\t\t\t\"code\": \"name_resid\"\n"
          + "\t\t}, {\n"
          + "\t\t\t\"name\": \"bank\",\n"
          + "\t\t\t\"tableCode\": \"BankTreeViewVO\",\n"
          + "\t\t\t\"code\": \"bank\",\n"
          + "\t\t\t\"dataType\": \"String\"\n"
          + "\t\t}],\n"
          + "\t\t\"operDefs\": [{\n"
          + "\t\t\t\"operId\": \"126fa209-3b07-4135-88e8-4badb61d794b\",\n"
          + "\t\t\t\"operType\": \"select\",\n"
          + "\t\t\t\"code\": \"modifier\",\n"
          + "\t\t\t\"name\": \"modifier\",\n"
          + "\t\t\t\"paramaters\": {\n"
          + "\t\t\t\t\"fieldCode\": \"modifier\",\n"
          + "\t\t\t\t\"dataType\": \"String\",\n"
          + "\t\t\t\t\"tableCode\": \"BankTreeViewVO\",\n"
          + "\t\t\t\t\"fieldType\": \"DIMENSION\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"displayName\": \"修改人\",\n"
          + "\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\"id\": \"String\",\n"
          + "\t\t\t\t\"name\": \"字符型\",\n"
          + "\t\t\t\t\"uri\": \"String\",\n"
          + "\t\t\t\t\"metaType\": \"PrimitiveType\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"terms\": [],\n"
          + "\t\t\t\"metaClassId\": \"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\n"
          + "\t\t\t\"tableCode\": \"BankTreeViewVO\"\n"
          + "\t\t}, {\n"
          + "\t\t\t\"operId\": \"83e2fc3e-57e0-4ee1-a5fe-86c3d323dc58\",\n"
          + "\t\t\t\"operType\": \"select\",\n"
          + "\t\t\t\"code\": \"dr\",\n"
          + "\t\t\t\"name\": \"dr\",\n"
          + "\t\t\t\"paramaters\": {\n"
          + "\t\t\t\t\"fieldCode\": \"dr\",\n"
          + "\t\t\t\t\"dataType\": \"Short\",\n"
          + "\t\t\t\t\"tableCode\": \"BankTreeViewVO\",\n"
          + "\t\t\t\t\"fieldType\": \"DIMENSION\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"displayName\": \"逻辑删除标记\",\n"
          + "\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\"id\": \"Short\",\n"
          + "\t\t\t\t\"name\": \"短整数\",\n"
          + "\t\t\t\t\"uri\": \"Short\",\n"
          + "\t\t\t\t\"metaType\": \"PrimitiveType\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"terms\": [{\n"
          + "\t\t\t\t\"_id\": {\n"
          + "\t\t\t\t\t\"$oid\": \"5cdfa460dd026f004e51d025\"\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"code\": \"DRFLAG\",\n"
          + "\t\t\t\t\"name\": \"删除标志\",\n"
          + "\t\t\t\t\"description\": \"\",\n"
          + "\t\t\t\t\"targetType\": \"PROPERTY\",\n"
          + "\t\t\t\t\"id\": \"dea521fb-2e9c-4d96-8461-949a9b8121fa\",\n"
          + "\t\t\t\t\"categories\": [{\n"
          + "\t\t\t\t\t\"code\": \"specialAttr\",\n"
          + "\t\t\t\t\t\"modifyTime\": \"2019-05-18 14:20:11:134\",\n"
          + "\t\t\t\t\t\"createTime\": \"2019-05-18 14:20:11:134\",\n"
          + "\t\t\t\t\t\"name\": \"特殊属性\",\n"
          + "\t\t\t\t\t\"description\": \"\",\n"
          + "\t\t\t\t\t\"_id\": {\n"
          + "\t\t\t\t\t\t\"$oid\": \"5cdfa41bdd026f004e51d023\"\n"
          + "\t\t\t\t\t},\n"
          + "\t\t\t\t\t\"id\": \"9979b678-6613-45e7-bcc0-fb4ce330df4b\",\n"
          + "\t\t\t\t\t\"parentId\": \"0\",\n"
          + "\t\t\t\t\t\"mul_language\": {\n"
          + "\t\t\t\t\t\t\"zh_TW\": {},\n"
          + "\t\t\t\t\t\t\"en_US\": {},\n"
          + "\t\t\t\t\t\t\"zh_CN\": {\n"
          + "\t\t\t\t\t\t\t\"name\": \"特殊属性\"\n"
          + "\t\t\t\t\t\t}\n"
          + "\t\t\t\t\t}\n"
          + "\t\t\t\t}],\n"
          + "\t\t\t\t\"mul_language\": {\n"
          + "\t\t\t\t\t\"zh_TW\": {},\n"
          + "\t\t\t\t\t\"en_US\": {},\n"
          + "\t\t\t\t\t\"zh_CN\": {\n"
          + "\t\t\t\t\t\t\"name\": \"删除标志\"\n"
          + "\t\t\t\t\t}\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"createTime\": \"2019-05-18 14:21:20:985\",\n"
          + "\t\t\t\t\"modifyTime\": \"2019-05-18 14:22:04:363\",\n"
          + "\t\t\t\t\"version\": 1\n"
          + "\t\t\t}],\n"
          + "\t\t\t\"metaClassId\": \"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\n"
          + "\t\t\t\"tableCode\": \"BankTreeViewVO\"\n"
          + "\t\t}, {\n"
          + "\t\t\t\"operId\": \"71f1489e-9182-4301-b41d-2bc33be896be\",\n"
          + "\t\t\t\"operType\": \"select\",\n"
          + "\t\t\t\"code\": \"code\",\n"
          + "\t\t\t\"name\": \"code\",\n"
          + "\t\t\t\"paramaters\": {\n"
          + "\t\t\t\t\"fieldCode\": \"code\",\n"
          + "\t\t\t\t\"dataType\": \"String\",\n"
          + "\t\t\t\t\"tableCode\": \"BankDotVO\",\n"
          + "\t\t\t\t\"fieldType\": \"DIMENSION\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"displayName\": \"编码\",\n"
          + "\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\"id\": \"String\",\n"
          + "\t\t\t\t\"name\": \"字符型\",\n"
          + "\t\t\t\t\"uri\": \"String\",\n"
          + "\t\t\t\t\"metaType\": \"PrimitiveType\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"terms\": [{\n"
          + "\t\t\t\t\"_id\": {\n"
          + "\t\t\t\t\t\"$oid\": \"5d67abd803ff9c0060a9d3d0\"\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"code\": \"isCode\",\n"
          + "\t\t\t\t\"name\": \"单据号\",\n"
          + "\t\t\t\t\"description\": \"isCode\",\n"
          + "\t\t\t\t\"targetType\": \"\",\n"
          + "\t\t\t\t\"id\": \"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\n"
          + "\t\t\t\t\"categories\": [{\n"
          + "\t\t\t\t\t\"code\": \"flow\",\n"
          + "\t\t\t\t\t\"modifyTime\": \"2020-06-13 14:47:44:975\",\n"
          + "\t\t\t\t\t\"createTime\": \"2020-06-13 14:47:44:975\",\n"
          + "\t\t\t\t\t\"name\": \"流程\",\n"
          + "\t\t\t\t\t\"description\": \"\",\n"
          + "\t\t\t\t\t\"_id\": {\n"
          + "\t\t\t\t\t\t\"$oid\": \"5ee476902c5df9005fdd5ad4\"\n"
          + "\t\t\t\t\t},\n"
          + "\t\t\t\t\t\"id\": \"0f8c698f-d881-4a73-be89-5a95ee5ba391\",\n"
          + "\t\t\t\t\t\"parentId\": \"0\",\n"
          + "\t\t\t\t\t\"mul_language\": {\n"
          + "\t\t\t\t\t\t\"zh_TW\": {},\n"
          + "\t\t\t\t\t\t\"en_US\": {},\n"
          + "\t\t\t\t\t\t\"zh_CN\": {\n"
          + "\t\t\t\t\t\t\t\"name\": \"流程\"\n"
          + "\t\t\t\t\t\t}\n"
          + "\t\t\t\t\t}\n"
          + "\t\t\t\t}],\n"
          + "\t\t\t\t\"mul_language\": {\n"
          + "\t\t\t\t\t\"zh_TW\": {},\n"
          + "\t\t\t\t\t\"en_US\": {},\n"
          + "\t\t\t\t\t\"zh_CN\": {\n"
          + "\t\t\t\t\t\t\"name\": \"单据号\"\n"
          + "\t\t\t\t\t}\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"createTime\": \"2019-08-29 18:41:28:693\",\n"
          + "\t\t\t\t\"modifyTime\": \"2020-06-13 14:48:23:468\",\n"
          + "\t\t\t\t\"version\": 2,\n"
          + "\t\t\t\t\"xmlTag\": \"isCode\",\n"
          + "\t\t\t\t\"refpk\": \"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\n"
          + "\t\t\t\t\"key\": \"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\n"
          + "\t\t\t\t\"refcode\": \"isCode\",\n"
          + "\t\t\t\t\"refname\": \"单据号\",\n"
          + "\t\t\t\t\"memo\": \"isCode\"\n"
          + "\t\t\t}],\n"
          + "\t\t\t\"metaClassId\": \"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\n"
          + "\t\t\t\"tableCode\": \"BankDotVO\"\n"
          + "\t\t}, {\n"
          + "\t\t\t\"operId\": \"b5ed8731-718f-40d7-981e-c78e6e7ba145\",\n"
          + "\t\t\t\"operType\": \"select\",\n"
          + "\t\t\t\"code\": \"name_resid\",\n"
          + "\t\t\t\"name\": \"name_resid\",\n"
          + "\t\t\t\"paramaters\": {\n"
          + "\t\t\t\t\"fieldCode\": \"name_resid\",\n"
          + "\t\t\t\t\"tableCode\": \"BankDotVO\",\n"
          + "\t\t\t\t\"fieldType\": \"DIMENSION\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"displayName\": \"多语资源id\",\n"
          + "\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\"name\": \"字符型\",\n"
          + "\t\t\t\t\"id\": \"String\",\n"
          + "\t\t\t\t\"metaType\": \"PrimitiveType\",\n"
          + "\t\t\t\t\"uri\": \"String\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"terms\": [],\n"
          + "\t\t\t\"metaClassId\": \"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\n"
          + "\t\t\t\"tableCode\": \"BankDotVO\"\n"
          + "\t\t}, {\n"
          + "\t\t\t\"operId\": \"276d84cb-245b-4db4-ad6d-b6498abe9f41\",\n"
          + "\t\t\t\"operType\": \"select\",\n"
          + "\t\t\t\"code\": \"bank\",\n"
          + "\t\t\t\"name\": \"bank\",\n"
          + "\t\t\t\"paramaters\": {\n"
          + "\t\t\t\t\"fieldCode\": \"bank\",\n"
          + "\t\t\t\t\"dataType\": \"String\",\n"
          + "\t\t\t\t\"tableCode\": \"BankTreeViewVO\",\n"
          + "\t\t\t\t\"fieldType\": \"DIMENSION\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"displayName\": \"社会级银行类别\",\n"
          + "\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\"id\": \"String\",\n"
          + "\t\t\t\t\"name\": \"字符型\",\n"
          + "\t\t\t\t\"uri\": \"String\",\n"
          + "\t\t\t\t\"metaType\": \"PrimitiveType\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"terms\": [],\n"
          + "\t\t\t\"metaClassId\": \"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\n"
          + "\t\t\t\"tableCode\": \"BankTreeViewVO\"\n"
          + "\t\t}],\n"
          + "\t\t\"fileds\": [{\n"
          + "\t\t\t\"name\": \"modifier\",\n"
          + "\t\t\t\"fieldName\": \"modifier\",\n"
          + "\t\t\t\"displayName\": \"修改人\",\n"
          + "\t\t\t\"type\": \"String\",\n"
          + "\t\t\t\"length\": \"36\",\n"
          + "\t\t\t\"id\": \"126fa209-3b07-4135-88e8-4badb61d794b\",\n"
          + "\t\t\t\"uri\": \"bd.bank.BankTreeViewVO.modifier\",\n"
          + "\t\t\t\"parentUri\": \"bd.bank.BankTreeViewVO\",\n"
          + "\t\t\t\"nullable\": true,\n"
          + "\t\t\t\"terms\": [],\n"
          + "\t\t\t\"metaType\": \"Property\",\n"
          + "\t\t\t\"modelType\": \"EntityAttrModel\",\n"
          + "\t\t\t\"version\": 13,\n"
          + "\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\"id\": \"String\",\n"
          + "\t\t\t\t\"name\": \"字符型\",\n"
          + "\t\t\t\t\"uri\": \"String\",\n"
          + "\t\t\t\t\"metaType\": \"PrimitiveType\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"key\": false,\n"
          + "\t\t\t\"precise\": \"2\",\n"
          + "\t\t\t\"isKey\": false,\n"
          + "\t\t\t\"isNewDataName\": false,\n"
          + "\t\t\t\"isNewDataCode\": false,\n"
          + "\t\t\t\"is_mul_language\": false,\n"
          + "\t\t\t\"isUnique\": false,\n"
          + "\t\t\t\"_key\": \"126fa209-3b07-4135-88e8-4badb61d794b\",\n"
          + "\t\t\t\"categoriesString\": \"\",\n"
          + "\t\t\t\"mul_language_resid\": {\n"
          + "\t\t\t\t\"displayName\": \"P_YS_PF_GZTORG_0000035173\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"code\": \"modifier\",\n"
          + "\t\t\t\"metaClassId\": \"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\n"
          + "\t\t\t\"oriName\": \"modifier\"\n"
          + "\t\t}, {\n"
          + "\t\t\t\"fieldName\": \"dr\",\n"
          + "\t\t\t\"key\": false,\n"
          + "\t\t\t\"nullable\": false,\n"
          + "\t\t\t\"length\": \"1\",\n"
          + "\t\t\t\"precise\": \"2\",\n"
          + "\t\t\t\"uri\": \"basedoc.basedocentity.BasedocBizObject.dr\",\n"
          + "\t\t\t\"name\": \"dr\",\n"
          + "\t\t\t\"displayName\": \"逻辑删除标记\",\n"
          + "\t\t\t\"type\": \"Short\",\n"
          + "\t\t\t\"id\": \"83e2fc3e-57e0-4ee1-a5fe-86c3d323dc58\",\n"
          + "\t\t\t\"parentUri\": \"basedoc.basedocentity.BasedocBizObject\",\n"
          + "\t\t\t\"terms\": [{\n"
          + "\t\t\t\t\"_id\": {\n"
          + "\t\t\t\t\t\"$oid\": \"5cdfa460dd026f004e51d025\"\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"code\": \"DRFLAG\",\n"
          + "\t\t\t\t\"name\": \"删除标志\",\n"
          + "\t\t\t\t\"description\": \"\",\n"
          + "\t\t\t\t\"targetType\": \"PROPERTY\",\n"
          + "\t\t\t\t\"id\": \"dea521fb-2e9c-4d96-8461-949a9b8121fa\",\n"
          + "\t\t\t\t\"categories\": [{\n"
          + "\t\t\t\t\t\"code\": \"specialAttr\",\n"
          + "\t\t\t\t\t\"modifyTime\": \"2019-05-18 14:20:11:134\",\n"
          + "\t\t\t\t\t\"createTime\": \"2019-05-18 14:20:11:134\",\n"
          + "\t\t\t\t\t\"name\": \"特殊属性\",\n"
          + "\t\t\t\t\t\"description\": \"\",\n"
          + "\t\t\t\t\t\"_id\": {\n"
          + "\t\t\t\t\t\t\"$oid\": \"5cdfa41bdd026f004e51d023\"\n"
          + "\t\t\t\t\t},\n"
          + "\t\t\t\t\t\"id\": \"9979b678-6613-45e7-bcc0-fb4ce330df4b\",\n"
          + "\t\t\t\t\t\"parentId\": \"0\",\n"
          + "\t\t\t\t\t\"mul_language\": {\n"
          + "\t\t\t\t\t\t\"zh_TW\": {},\n"
          + "\t\t\t\t\t\t\"en_US\": {},\n"
          + "\t\t\t\t\t\t\"zh_CN\": {\n"
          + "\t\t\t\t\t\t\t\"name\": \"特殊属性\"\n"
          + "\t\t\t\t\t\t}\n"
          + "\t\t\t\t\t}\n"
          + "\t\t\t\t}],\n"
          + "\t\t\t\t\"mul_language\": {\n"
          + "\t\t\t\t\t\"zh_TW\": {},\n"
          + "\t\t\t\t\t\"en_US\": {},\n"
          + "\t\t\t\t\t\"zh_CN\": {\n"
          + "\t\t\t\t\t\t\"name\": \"删除标志\"\n"
          + "\t\t\t\t\t}\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"createTime\": \"2019-05-18 14:21:20:985\",\n"
          + "\t\t\t\t\"modifyTime\": \"2019-05-18 14:22:04:363\",\n"
          + "\t\t\t\t\"version\": 1\n"
          + "\t\t\t}],\n"
          + "\t\t\t\"metaType\": \"Property\",\n"
          + "\t\t\t\"modelType\": \"EntityAttrModel\",\n"
          + "\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\"id\": \"Short\",\n"
          + "\t\t\t\t\"name\": \"短整数\",\n"
          + "\t\t\t\t\"uri\": \"Short\",\n"
          + "\t\t\t\t\"metaType\": \"PrimitiveType\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"version\": 12,\n"
          + "\t\t\t\"defaultValue\": \"0\",\n"
          + "\t\t\t\"isKey\": false,\n"
          + "\t\t\t\"isNewDataName\": false,\n"
          + "\t\t\t\"isNewDataCode\": false,\n"
          + "\t\t\t\"_key\": \"83e2fc3e-57e0-4ee1-a5fe-86c3d323dc58\",\n"
          + "\t\t\t\"categoriesString\": \"删除标志\",\n"
          + "\t\t\t\"mul_language_resid\": {\n"
          + "\t\t\t\t\"displayName\": \"P_YS_PF_GZTTMP_0000073434\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"code\": \"dr\",\n"
          + "\t\t\t\"metaClassId\": \"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\n"
          + "\t\t\t\"oriName\": \"dr\"\n"
          + "\t\t}, {\n"
          + "\t\t\t\"name\": \"code\",\n"
          + "\t\t\t\"fieldName\": \"code\",\n"
          + "\t\t\t\"displayName\": \"编码\",\n"
          + "\t\t\t\"type\": \"String\",\n"
          + "\t\t\t\"length\": \"100\",\n"
          + "\t\t\t\"id\": \"71f1489e-9182-4301-b41d-2bc33be896be\",\n"
          + "\t\t\t\"uri\": \"bd.bank.BankDotVO.code\",\n"
          + "\t\t\t\"parentUri\": \"bd.bank.BankDotVO\",\n"
          + "\t\t\t\"nullable\": false,\n"
          + "\t\t\t\"terms\": [{\n"
          + "\t\t\t\t\"_id\": {\n"
          + "\t\t\t\t\t\"$oid\": \"5d67abd803ff9c0060a9d3d0\"\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"code\": \"isCode\",\n"
          + "\t\t\t\t\"name\": \"单据号\",\n"
          + "\t\t\t\t\"description\": \"isCode\",\n"
          + "\t\t\t\t\"targetType\": \"\",\n"
          + "\t\t\t\t\"id\": \"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\n"
          + "\t\t\t\t\"categories\": [{\n"
          + "\t\t\t\t\t\"code\": \"flow\",\n"
          + "\t\t\t\t\t\"modifyTime\": \"2020-06-13 14:47:44:975\",\n"
          + "\t\t\t\t\t\"createTime\": \"2020-06-13 14:47:44:975\",\n"
          + "\t\t\t\t\t\"name\": \"流程\",\n"
          + "\t\t\t\t\t\"description\": \"\",\n"
          + "\t\t\t\t\t\"_id\": {\n"
          + "\t\t\t\t\t\t\"$oid\": \"5ee476902c5df9005fdd5ad4\"\n"
          + "\t\t\t\t\t},\n"
          + "\t\t\t\t\t\"id\": \"0f8c698f-d881-4a73-be89-5a95ee5ba391\",\n"
          + "\t\t\t\t\t\"parentId\": \"0\",\n"
          + "\t\t\t\t\t\"mul_language\": {\n"
          + "\t\t\t\t\t\t\"zh_TW\": {},\n"
          + "\t\t\t\t\t\t\"en_US\": {},\n"
          + "\t\t\t\t\t\t\"zh_CN\": {\n"
          + "\t\t\t\t\t\t\t\"name\": \"流程\"\n"
          + "\t\t\t\t\t\t}\n"
          + "\t\t\t\t\t}\n"
          + "\t\t\t\t}],\n"
          + "\t\t\t\t\"mul_language\": {\n"
          + "\t\t\t\t\t\"zh_TW\": {},\n"
          + "\t\t\t\t\t\"en_US\": {},\n"
          + "\t\t\t\t\t\"zh_CN\": {\n"
          + "\t\t\t\t\t\t\"name\": \"单据号\"\n"
          + "\t\t\t\t\t}\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"createTime\": \"2019-08-29 18:41:28:693\",\n"
          + "\t\t\t\t\"modifyTime\": \"2020-06-13 14:48:23:468\",\n"
          + "\t\t\t\t\"version\": 2,\n"
          + "\t\t\t\t\"xmlTag\": \"isCode\",\n"
          + "\t\t\t\t\"refpk\": \"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\n"
          + "\t\t\t\t\"key\": \"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\n"
          + "\t\t\t\t\"refcode\": \"isCode\",\n"
          + "\t\t\t\t\"refname\": \"单据号\",\n"
          + "\t\t\t\t\"memo\": \"isCode\"\n"
          + "\t\t\t}],\n"
          + "\t\t\t\"metaType\": \"Property\",\n"
          + "\t\t\t\"modelType\": \"EntityAttrModel\",\n"
          + "\t\t\t\"version\": 21,\n"
          + "\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\"id\": \"String\",\n"
          + "\t\t\t\t\"name\": \"字符型\",\n"
          + "\t\t\t\t\"uri\": \"String\",\n"
          + "\t\t\t\t\"metaType\": \"PrimitiveType\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"isKey\": false,\n"
          + "\t\t\t\"precise\": \"2\",\n"
          + "\t\t\t\"isUnique\": true,\n"
          + "\t\t\t\"isRequired\": true,\n"
          + "\t\t\t\"createTime\": \"2019-09-04 17:30:52:458\",\n"
          + "\t\t\t\"modifyTime\": \"2019-09-04 17:30:52:458\",\n"
          + "\t\t\t\"_key\": \"71f1489e-9182-4301-b41d-2bc33be896be\",\n"
          + "\t\t\t\"isNewDataName\": false,\n"
          + "\t\t\t\"isNewDataCode\": false,\n"
          + "\t\t\t\"is_mul_language\": false,\n"
          + "\t\t\t\"mul_language_resid\": {\n"
          + "\t\t\t\t\"displayName\": \"P_YS_FED_EXAMP_0000020286\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"categoriesString\": \"单据号\",\n"
          + "\t\t\t\"key\": false,\n"
          + "\t\t\t\"isCode\": true,\n"
          + "\t\t\t\"code\": \"code\",\n"
          + "\t\t\t\"metaClassId\": \"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\n"
          + "\t\t\t\"oriName\": \"code\"\n"
          + "\t\t}, {\n"
          + "\t\t\t\"displayName\": \"多语资源id\",\n"
          + "\t\t\t\"name\": \"name_resid\",\n"
          + "\t\t\t\"fieldName\": \"name_resid\",\n"
          + "\t\t\t\"id\": \"b5ed8731-718f-40d7-981e-c78e6e7ba145\",\n"
          + "\t\t\t\"isNewDataName\": false,\n"
          + "\t\t\t\"isNewDataCode\": false,\n"
          + "\t\t\t\"nullable\": \"true\",\n"
          + "\t\t\t\"length\": 256,\n"
          + "\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\"name\": \"字符型\",\n"
          + "\t\t\t\t\"id\": \"String\",\n"
          + "\t\t\t\t\"metaType\": \"PrimitiveType\",\n"
          + "\t\t\t\t\"uri\": \"String\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"precise\": \"2\",\n"
          + "\t\t\t\"uri\": \"bd.bank.BankDotVO.name_resid\",\n"
          + "\t\t\t\"tenantId\": \"sys\",\n"
          + "\t\t\t\"metadataLevel\": \"0\",\n"
          + "\t\t\t\"modelType\": \"EntityAttrModel\",\n"
          + "\t\t\t\"metaType\": \"Property\",\n"
          + "\t\t\t\"version\": 4,\n"
          + "\t\t\t\"createTime\": \"2020-05-13 09:48:17:067\",\n"
          + "\t\t\t\"modifyTime\": \"2020-05-13 09:48:17:067\",\n"
          + "\t\t\t\"terms\": [],\n"
          + "\t\t\t\"_key\": \"b5ed8731-718f-40d7-981e-c78e6e7ba145\",\n"
          + "\t\t\t\"categoriesString\": \"\",\n"
          + "\t\t\t\"mul_language_resid\": {\n"
          + "\t\t\t\t\"displayName\": \"P_YS_PF_METADATA_0001077410\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"is_mul_language\": false,\n"
          + "\t\t\t\"code\": \"name_resid\",\n"
          + "\t\t\t\"metaClassId\": \"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\n"
          + "\t\t\t\"oriName\": \"name_resid\"\n"
          + "\t\t}, {\n"
          + "\t\t\t\"name\": \"bank\",\n"
          + "\t\t\t\"fieldName\": \"bank\",\n"
          + "\t\t\t\"displayName\": \"社会级银行类别\",\n"
          + "\t\t\t\"type\": \"String\",\n"
          + "\t\t\t\"length\": \"36\",\n"
          + "\t\t\t\"id\": \"276d84cb-245b-4db4-ad6d-b6498abe9f41\",\n"
          + "\t\t\t\"uri\": \"bd.bank.BankTreeViewVO.bank\",\n"
          + "\t\t\t\"parentUri\": \"bd.bank.BankTreeViewVO\",\n"
          + "\t\t\t\"nullable\": true,\n"
          + "\t\t\t\"terms\": [],\n"
          + "\t\t\t\"metaType\": \"Property\",\n"
          + "\t\t\t\"modelType\": \"EntityAttrModel\",\n"
          + "\t\t\t\"version\": 3,\n"
          + "\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\"id\": \"String\",\n"
          + "\t\t\t\t\"name\": \"字符型\",\n"
          + "\t\t\t\t\"uri\": \"String\",\n"
          + "\t\t\t\t\"metaType\": \"PrimitiveType\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"key\": false,\n"
          + "\t\t\t\"precise\": \"2\",\n"
          + "\t\t\t\"isKey\": false,\n"
          + "\t\t\t\"isNewDataName\": false,\n"
          + "\t\t\t\"isNewDataCode\": false,\n"
          + "\t\t\t\"is_mul_language\": false,\n"
          + "\t\t\t\"isUnique\": false,\n"
          + "\t\t\t\"_key\": \"276d84cb-245b-4db4-ad6d-b6498abe9f41\",\n"
          + "\t\t\t\"categoriesString\": \"\",\n"
          + "\t\t\t\"mul_language_resid\": {\n"
          + "\t\t\t\t\"displayName\": \"P_YS_PF_METADATA_0000084990\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"serialNumber\": 210,\n"
          + "\t\t\t\"code\": \"bank\",\n"
          + "\t\t\t\"metaClassId\": \"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\n"
          + "\t\t\t\"oriName\": \"bank\"\n"
          + "\t\t}],\n"
          + "\t\t\"joinGeneral\": {\n"
          + "\t\t\t\"general\": [{\n"
          + "\t\t\t\t\"id\": \"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\n"
          + "\t\t\t\t\"objID\": \"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\n"
          + "\t\t\t\t\"objName\": \"银行类别\",\n"
          + "\t\t\t\t\"objTable\": \"银行类别\",\n"
          + "\t\t\t\t\"objComment\": \"银行类别\",\n"
          + "\t\t\t\t\"objCode\": \"BankTreeViewVO\",\n"
          + "\t\t\t\t\"objType\": 29,\n"
          + "\t\t\t\t\"includeTenant\": true,\n"
          + "\t\t\t\t\"parentId\": \"\",\n"
          + "\t\t\t\t\"x\": 50,\n"
          + "\t\t\t\t\"y\": 138\n"
          + "\t\t\t}, {\n"
          + "\t\t\t\t\"id\": \"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\n"
          + "\t\t\t\t\"objID\": \"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\n"
          + "\t\t\t\t\"objName\": \"银行网点\",\n"
          + "\t\t\t\t\"objTable\": \"银行网点\",\n"
          + "\t\t\t\t\"objComment\": \"银行网点\",\n"
          + "\t\t\t\t\"objCode\": \"BankDotVO\",\n"
          + "\t\t\t\t\"objType\": 29,\n"
          + "\t\t\t\t\"includeTenant\": true,\n"
          + "\t\t\t\t\"parentId\": \"\",\n"
          + "\t\t\t\t\"x\": 598,\n"
          + "\t\t\t\t\"y\": 144\n"
          + "\t\t\t}],\n"
          + "\t\t\t\"links\": [{\n"
          + "\t\t\t\t\"dataRelation\": \"Join\",\n"
          + "\t\t\t\t\"linkType\": \"InnerJoin\",\n"
          + "\t\t\t\t\"leftKey\": \"name\",\n"
          + "\t\t\t\t\"rightKey\": \"sysid\",\n"
          + "\t\t\t\t\"leftObjName\": \"银行类别\",\n"
          + "\t\t\t\t\"rightObjName\": \"银行网点\",\n"
          + "\t\t\t\t\"leftObjType\": 29,\n"
          + "\t\t\t\t\"rightObjType\": 29,\n"
          + "\t\t\t\t\"linkItems\": [{\n"
          + "\t\t\t\t\t\"leftFieldCode\": \"name\",\n"
          + "\t\t\t\t\t\"leftFieldType\": \"String\",\n"
          + "\t\t\t\t\t\"leftFieldFunc\": \"\",\n"
          + "\t\t\t\t\t\"rightFieldCode\": \"sysid\",\n"
          + "\t\t\t\t\t\"rightFieldType\": \"String\",\n"
          + "\t\t\t\t\t\"rightFieldFunc\": \"\"\n"
          + "\t\t\t\t}],\n"
          + "\t\t\t\t\"leftFieldType\": \"String\",\n"
          + "\t\t\t\t\"rightFieldType\": \"String\"\n"
          + "\t\t\t}]\n"
          + "\t\t},\n"
          + "\t\t\"links\": [{\n"
          + "\t\t\t\"dataRelation\": \"Join\",\n"
          + "\t\t\t\"linkType\": \"InnerJoin\",\n"
          + "\t\t\t\"leftKey\": \"name\",\n"
          + "\t\t\t\"rightKey\": \"sysid\",\n"
          + "\t\t\t\"leftObjName\": \"bd.bank.BankTreeViewVO\",\n"
          + "\t\t\t\"rightObjName\": \"bd.bank.BankDotVO\",\n"
          + "\t\t\t\"leftObjType\": 29,\n"
          + "\t\t\t\"rightObjType\": 29,\n"
          + "\t\t\t\"linkItems\": [{\n"
          + "\t\t\t\t\"leftFieldCode\": \"name\",\n"
          + "\t\t\t\t\"leftFieldType\": \"String\",\n"
          + "\t\t\t\t\"leftFieldFunc\": \"\",\n"
          + "\t\t\t\t\"rightFieldCode\": \"sysid\",\n"
          + "\t\t\t\t\"rightFieldType\": \"String\",\n"
          + "\t\t\t\t\"rightFieldFunc\": \"\"\n"
          + "\t\t\t}],\n"
          + "\t\t\t\"leftFieldType\": \"String\",\n"
          + "\t\t\t\"rightFieldType\": \"String\",\n"
          + "\t\t\t\"leftObjId\": \"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\n"
          + "\t\t\t\"rightObjId\": \"47a69dfe-37ef-4ad1-aa19-1d61797a7821\"\n"
          + "\t\t}],\n"
          + "\t\t\"info\": {\n"
          + "\t\t\t\"dataSource\": {},\n"
          + "\t\t\t\"tableCodes\": {\n"
          + "\t\t\t\t\"#intellivtc1\": \"银行类别\",\n"
          + "\t\t\t\t\"#intellivtc2\": \"银行网点\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"tableIds\": {\n"
          + "\t\t\t\t\"#intellivtid1\": \"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\n"
          + "\t\t\t\t\"#intellivtid2\": \"47a69dfe-37ef-4ad1-aa19-1d61797a7821\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"tableSourceRel\": {},\n"
          + "\t\t\t\"codes\": {\n"
          + "\t\t\t\t\"#intellivtc1\": \"BankTreeViewVO\",\n"
          + "\t\t\t\t\"#intellivtc2\": \"BankDotVO\"\n"
          + "\t\t\t}\n"
          + "\t\t},\n"
          + "\t\t\"obj\": {\n"
          + "\t\t\t\"name\": \"test019\",\n"
          + "\t\t\t\"code\": \"test019\",\n"
          + "\t\t\t\"reportType\": \"1\"\n"
          + "\t\t},\n"
          + "\t\t\"querySchema\": {\n"
          + "\t\t\t\"fields\": [{\n"
          + "\t\t\t\t\"name\": \"modifier\",\n"
          + "\t\t\t\t\"fieldName\": \"modifier\",\n"
          + "\t\t\t\t\"displayName\": \"修改人\",\n"
          + "\t\t\t\t\"type\": \"String\",\n"
          + "\t\t\t\t\"length\": \"36\",\n"
          + "\t\t\t\t\"id\": \"126fa209-3b07-4135-88e8-4badb61d794b\",\n"
          + "\t\t\t\t\"uri\": \"bd.bank.BankTreeViewVO.modifier\",\n"
          + "\t\t\t\t\"parentUri\": \"bd.bank.BankTreeViewVO\",\n"
          + "\t\t\t\t\"nullable\": true,\n"
          + "\t\t\t\t\"terms\": [],\n"
          + "\t\t\t\t\"metaType\": \"Property\",\n"
          + "\t\t\t\t\"modelType\": \"EntityAttrModel\",\n"
          + "\t\t\t\t\"version\": 13,\n"
          + "\t\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\t\"id\": \"String\",\n"
          + "\t\t\t\t\t\"name\": \"字符型\",\n"
          + "\t\t\t\t\t\"uri\": \"String\",\n"
          + "\t\t\t\t\t\"metaType\": \"PrimitiveType\"\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"key\": false,\n"
          + "\t\t\t\t\"precise\": \"2\",\n"
          + "\t\t\t\t\"isKey\": false,\n"
          + "\t\t\t\t\"isNewDataName\": false,\n"
          + "\t\t\t\t\"isNewDataCode\": false,\n"
          + "\t\t\t\t\"is_mul_language\": false,\n"
          + "\t\t\t\t\"isUnique\": false,\n"
          + "\t\t\t\t\"_key\": \"126fa209-3b07-4135-88e8-4badb61d794b\",\n"
          + "\t\t\t\t\"categoriesString\": \"\",\n"
          + "\t\t\t\t\"mul_language_resid\": {\n"
          + "\t\t\t\t\t\"displayName\": \"P_YS_PF_GZTORG_0000035173\"\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"code\": \"modifier\",\n"
          + "\t\t\t\t\"metaClassId\": \"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\n"
          + "\t\t\t\t\"oriName\": \"modifier\"\n"
          + "\t\t\t}, {\n"
          + "\t\t\t\t\"fieldName\": \"dr\",\n"
          + "\t\t\t\t\"key\": false,\n"
          + "\t\t\t\t\"nullable\": false,\n"
          + "\t\t\t\t\"length\": \"1\",\n"
          + "\t\t\t\t\"precise\": \"2\",\n"
          + "\t\t\t\t\"uri\": \"basedoc.basedocentity.BasedocBizObject.dr\",\n"
          + "\t\t\t\t\"name\": \"dr\",\n"
          + "\t\t\t\t\"displayName\": \"逻辑删除标记\",\n"
          + "\t\t\t\t\"type\": \"Short\",\n"
          + "\t\t\t\t\"id\": \"83e2fc3e-57e0-4ee1-a5fe-86c3d323dc58\",\n"
          + "\t\t\t\t\"parentUri\": \"basedoc.basedocentity.BasedocBizObject\",\n"
          + "\t\t\t\t\"terms\": [{\n"
          + "\t\t\t\t\t\"_id\": {\n"
          + "\t\t\t\t\t\t\"$oid\": \"5cdfa460dd026f004e51d025\"\n"
          + "\t\t\t\t\t},\n"
          + "\t\t\t\t\t\"code\": \"DRFLAG\",\n"
          + "\t\t\t\t\t\"name\": \"删除标志\",\n"
          + "\t\t\t\t\t\"description\": \"\",\n"
          + "\t\t\t\t\t\"targetType\": \"PROPERTY\",\n"
          + "\t\t\t\t\t\"id\": \"dea521fb-2e9c-4d96-8461-949a9b8121fa\",\n"
          + "\t\t\t\t\t\"categories\": [{\n"
          + "\t\t\t\t\t\t\"code\": \"specialAttr\",\n"
          + "\t\t\t\t\t\t\"modifyTime\": \"2019-05-18 14:20:11:134\",\n"
          + "\t\t\t\t\t\t\"createTime\": \"2019-05-18 14:20:11:134\",\n"
          + "\t\t\t\t\t\t\"name\": \"特殊属性\",\n"
          + "\t\t\t\t\t\t\"description\": \"\",\n"
          + "\t\t\t\t\t\t\"_id\": {\n"
          + "\t\t\t\t\t\t\t\"$oid\": \"5cdfa41bdd026f004e51d023\"\n"
          + "\t\t\t\t\t\t},\n"
          + "\t\t\t\t\t\t\"id\": \"9979b678-6613-45e7-bcc0-fb4ce330df4b\",\n"
          + "\t\t\t\t\t\t\"parentId\": \"0\",\n"
          + "\t\t\t\t\t\t\"mul_language\": {\n"
          + "\t\t\t\t\t\t\t\"zh_TW\": {},\n"
          + "\t\t\t\t\t\t\t\"en_US\": {},\n"
          + "\t\t\t\t\t\t\t\"zh_CN\": {\n"
          + "\t\t\t\t\t\t\t\t\"name\": \"特殊属性\"\n"
          + "\t\t\t\t\t\t\t}\n"
          + "\t\t\t\t\t\t}\n"
          + "\t\t\t\t\t}],\n"
          + "\t\t\t\t\t\"mul_language\": {\n"
          + "\t\t\t\t\t\t\"zh_TW\": {},\n"
          + "\t\t\t\t\t\t\"en_US\": {},\n"
          + "\t\t\t\t\t\t\"zh_CN\": {\n"
          + "\t\t\t\t\t\t\t\"name\": \"删除标志\"\n"
          + "\t\t\t\t\t\t}\n"
          + "\t\t\t\t\t},\n"
          + "\t\t\t\t\t\"createTime\": \"2019-05-18 14:21:20:985\",\n"
          + "\t\t\t\t\t\"modifyTime\": \"2019-05-18 14:22:04:363\",\n"
          + "\t\t\t\t\t\"version\": 1\n"
          + "\t\t\t\t}],\n"
          + "\t\t\t\t\"metaType\": \"Property\",\n"
          + "\t\t\t\t\"modelType\": \"EntityAttrModel\",\n"
          + "\t\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\t\"id\": \"Short\",\n"
          + "\t\t\t\t\t\"name\": \"短整数\",\n"
          + "\t\t\t\t\t\"uri\": \"Short\",\n"
          + "\t\t\t\t\t\"metaType\": \"PrimitiveType\"\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"version\": 12,\n"
          + "\t\t\t\t\"defaultValue\": \"0\",\n"
          + "\t\t\t\t\"isKey\": false,\n"
          + "\t\t\t\t\"isNewDataName\": false,\n"
          + "\t\t\t\t\"isNewDataCode\": false,\n"
          + "\t\t\t\t\"_key\": \"83e2fc3e-57e0-4ee1-a5fe-86c3d323dc58\",\n"
          + "\t\t\t\t\"categoriesString\": \"删除标志\",\n"
          + "\t\t\t\t\"mul_language_resid\": {\n"
          + "\t\t\t\t\t\"displayName\": \"P_YS_PF_GZTTMP_0000073434\"\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"code\": \"dr\",\n"
          + "\t\t\t\t\"metaClassId\": \"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\n"
          + "\t\t\t\t\"oriName\": \"dr\"\n"
          + "\t\t\t}, {\n"
          + "\t\t\t\t\"name\": \"code\",\n"
          + "\t\t\t\t\"fieldName\": \"code\",\n"
          + "\t\t\t\t\"displayName\": \"编码\",\n"
          + "\t\t\t\t\"type\": \"String\",\n"
          + "\t\t\t\t\"length\": \"100\",\n"
          + "\t\t\t\t\"id\": \"71f1489e-9182-4301-b41d-2bc33be896be\",\n"
          + "\t\t\t\t\"uri\": \"bd.bank.BankDotVO.code\",\n"
          + "\t\t\t\t\"parentUri\": \"bd.bank.BankDotVO\",\n"
          + "\t\t\t\t\"nullable\": false,\n"
          + "\t\t\t\t\"terms\": [{\n"
          + "\t\t\t\t\t\"_id\": {\n"
          + "\t\t\t\t\t\t\"$oid\": \"5d67abd803ff9c0060a9d3d0\"\n"
          + "\t\t\t\t\t},\n"
          + "\t\t\t\t\t\"code\": \"isCode\",\n"
          + "\t\t\t\t\t\"name\": \"单据号\",\n"
          + "\t\t\t\t\t\"description\": \"isCode\",\n"
          + "\t\t\t\t\t\"targetType\": \"\",\n"
          + "\t\t\t\t\t\"id\": \"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\n"
          + "\t\t\t\t\t\"categories\": [{\n"
          + "\t\t\t\t\t\t\"code\": \"flow\",\n"
          + "\t\t\t\t\t\t\"modifyTime\": \"2020-06-13 14:47:44:975\",\n"
          + "\t\t\t\t\t\t\"createTime\": \"2020-06-13 14:47:44:975\",\n"
          + "\t\t\t\t\t\t\"name\": \"流程\",\n"
          + "\t\t\t\t\t\t\"description\": \"\",\n"
          + "\t\t\t\t\t\t\"_id\": {\n"
          + "\t\t\t\t\t\t\t\"$oid\": \"5ee476902c5df9005fdd5ad4\"\n"
          + "\t\t\t\t\t\t},\n"
          + "\t\t\t\t\t\t\"id\": \"0f8c698f-d881-4a73-be89-5a95ee5ba391\",\n"
          + "\t\t\t\t\t\t\"parentId\": \"0\",\n"
          + "\t\t\t\t\t\t\"mul_language\": {\n"
          + "\t\t\t\t\t\t\t\"zh_TW\": {},\n"
          + "\t\t\t\t\t\t\t\"en_US\": {},\n"
          + "\t\t\t\t\t\t\t\"zh_CN\": {\n"
          + "\t\t\t\t\t\t\t\t\"name\": \"流程\"\n"
          + "\t\t\t\t\t\t\t}\n"
          + "\t\t\t\t\t\t}\n"
          + "\t\t\t\t\t}],\n"
          + "\t\t\t\t\t\"mul_language\": {\n"
          + "\t\t\t\t\t\t\"zh_TW\": {},\n"
          + "\t\t\t\t\t\t\"en_US\": {},\n"
          + "\t\t\t\t\t\t\"zh_CN\": {\n"
          + "\t\t\t\t\t\t\t\"name\": \"单据号\"\n"
          + "\t\t\t\t\t\t}\n"
          + "\t\t\t\t\t},\n"
          + "\t\t\t\t\t\"createTime\": \"2019-08-29 18:41:28:693\",\n"
          + "\t\t\t\t\t\"modifyTime\": \"2020-06-13 14:48:23:468\",\n"
          + "\t\t\t\t\t\"version\": 2,\n"
          + "\t\t\t\t\t\"xmlTag\": \"isCode\",\n"
          + "\t\t\t\t\t\"refpk\": \"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\n"
          + "\t\t\t\t\t\"key\": \"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\n"
          + "\t\t\t\t\t\"refcode\": \"isCode\",\n"
          + "\t\t\t\t\t\"refname\": \"单据号\",\n"
          + "\t\t\t\t\t\"memo\": \"isCode\"\n"
          + "\t\t\t\t}],\n"
          + "\t\t\t\t\"metaType\": \"Property\",\n"
          + "\t\t\t\t\"modelType\": \"EntityAttrModel\",\n"
          + "\t\t\t\t\"version\": 21,\n"
          + "\t\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\t\"id\": \"String\",\n"
          + "\t\t\t\t\t\"name\": \"字符型\",\n"
          + "\t\t\t\t\t\"uri\": \"String\",\n"
          + "\t\t\t\t\t\"metaType\": \"PrimitiveType\"\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"isKey\": false,\n"
          + "\t\t\t\t\"precise\": \"2\",\n"
          + "\t\t\t\t\"isUnique\": true,\n"
          + "\t\t\t\t\"isRequired\": true,\n"
          + "\t\t\t\t\"createTime\": \"2019-09-04 17:30:52:458\",\n"
          + "\t\t\t\t\"modifyTime\": \"2019-09-04 17:30:52:458\",\n"
          + "\t\t\t\t\"_key\": \"71f1489e-9182-4301-b41d-2bc33be896be\",\n"
          + "\t\t\t\t\"isNewDataName\": false,\n"
          + "\t\t\t\t\"isNewDataCode\": false,\n"
          + "\t\t\t\t\"is_mul_language\": false,\n"
          + "\t\t\t\t\"mul_language_resid\": {\n"
          + "\t\t\t\t\t\"displayName\": \"P_YS_FED_EXAMP_0000020286\"\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"categoriesString\": \"单据号\",\n"
          + "\t\t\t\t\"key\": false,\n"
          + "\t\t\t\t\"isCode\": true,\n"
          + "\t\t\t\t\"code\": \"code\",\n"
          + "\t\t\t\t\"metaClassId\": \"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\n"
          + "\t\t\t\t\"oriName\": \"code\"\n"
          + "\t\t\t}, {\n"
          + "\t\t\t\t\"displayName\": \"多语资源id\",\n"
          + "\t\t\t\t\"name\": \"name_resid\",\n"
          + "\t\t\t\t\"fieldName\": \"name_resid\",\n"
          + "\t\t\t\t\"id\": \"b5ed8731-718f-40d7-981e-c78e6e7ba145\",\n"
          + "\t\t\t\t\"isNewDataName\": false,\n"
          + "\t\t\t\t\"isNewDataCode\": false,\n"
          + "\t\t\t\t\"nullable\": \"true\",\n"
          + "\t\t\t\t\"length\": 256,\n"
          + "\t\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\t\"name\": \"字符型\",\n"
          + "\t\t\t\t\t\"id\": \"String\",\n"
          + "\t\t\t\t\t\"metaType\": \"PrimitiveType\",\n"
          + "\t\t\t\t\t\"uri\": \"String\"\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"precise\": \"2\",\n"
          + "\t\t\t\t\"uri\": \"bd.bank.BankDotVO.name_resid\",\n"
          + "\t\t\t\t\"tenantId\": \"sys\",\n"
          + "\t\t\t\t\"metadataLevel\": \"0\",\n"
          + "\t\t\t\t\"modelType\": \"EntityAttrModel\",\n"
          + "\t\t\t\t\"metaType\": \"Property\",\n"
          + "\t\t\t\t\"version\": 4,\n"
          + "\t\t\t\t\"createTime\": \"2020-05-13 09:48:17:067\",\n"
          + "\t\t\t\t\"modifyTime\": \"2020-05-13 09:48:17:067\",\n"
          + "\t\t\t\t\"terms\": [],\n"
          + "\t\t\t\t\"_key\": \"b5ed8731-718f-40d7-981e-c78e6e7ba145\",\n"
          + "\t\t\t\t\"categoriesString\": \"\",\n"
          + "\t\t\t\t\"mul_language_resid\": {\n"
          + "\t\t\t\t\t\"displayName\": \"P_YS_PF_METADATA_0001077410\"\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"is_mul_language\": false,\n"
          + "\t\t\t\t\"code\": \"name_resid\",\n"
          + "\t\t\t\t\"metaClassId\": \"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\n"
          + "\t\t\t\t\"oriName\": \"name_resid\"\n"
          + "\t\t\t}, {\n"
          + "\t\t\t\t\"name\": \"bank\",\n"
          + "\t\t\t\t\"fieldName\": \"bank\",\n"
          + "\t\t\t\t\"displayName\": \"社会级银行类别\",\n"
          + "\t\t\t\t\"type\": \"String\",\n"
          + "\t\t\t\t\"length\": \"36\",\n"
          + "\t\t\t\t\"id\": \"276d84cb-245b-4db4-ad6d-b6498abe9f41\",\n"
          + "\t\t\t\t\"uri\": \"bd.bank.BankTreeViewVO.bank\",\n"
          + "\t\t\t\t\"parentUri\": \"bd.bank.BankTreeViewVO\",\n"
          + "\t\t\t\t\"nullable\": true,\n"
          + "\t\t\t\t\"terms\": [],\n"
          + "\t\t\t\t\"metaType\": \"Property\",\n"
          + "\t\t\t\t\"modelType\": \"EntityAttrModel\",\n"
          + "\t\t\t\t\"version\": 3,\n"
          + "\t\t\t\t\"dataType\": {\n"
          + "\t\t\t\t\t\"id\": \"String\",\n"
          + "\t\t\t\t\t\"name\": \"字符型\",\n"
          + "\t\t\t\t\t\"uri\": \"String\",\n"
          + "\t\t\t\t\t\"metaType\": \"PrimitiveType\"\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"key\": false,\n"
          + "\t\t\t\t\"precise\": \"2\",\n"
          + "\t\t\t\t\"isKey\": false,\n"
          + "\t\t\t\t\"isNewDataName\": false,\n"
          + "\t\t\t\t\"isNewDataCode\": false,\n"
          + "\t\t\t\t\"is_mul_language\": false,\n"
          + "\t\t\t\t\"isUnique\": false,\n"
          + "\t\t\t\t\"_key\": \"276d84cb-245b-4db4-ad6d-b6498abe9f41\",\n"
          + "\t\t\t\t\"categoriesString\": \"\",\n"
          + "\t\t\t\t\"mul_language_resid\": {\n"
          + "\t\t\t\t\t\"displayName\": \"P_YS_PF_METADATA_0000084990\"\n"
          + "\t\t\t\t},\n"
          + "\t\t\t\t\"serialNumber\": 210,\n"
          + "\t\t\t\t\"code\": \"bank\",\n"
          + "\t\t\t\t\"metaClassId\": \"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\n"
          + "\t\t\t\t\"oriName\": \"bank\"\n"
          + "\t\t\t}],\n"
          + "\t\t\t\"pager\": {\n"
          + "\t\t\t\t\"pageIndex\": \"1\",\n"
          + "\t\t\t\t\"pageSize\": \"10\"\n"
          + "\t\t\t},\n"
          + "\t\t\t\"conditions\": []\n"
          + "\t\t},\n"
          + "\t\t\"paramList\": [],\n"
          + "\t\t\"fieldSeqs\": [\"modifier\", \"dr\", \"code\", \"name_resid\", \"bank\"]\n"
          + "\t},\n"
          + "\t\"info\": {\n"
          + "\t\t\"dataSource\": {},\n"
          + "\t\t\"tableCodes\": {\n"
          + "\t\t\t\"#intellivtc1\": \"银行类别\",\n"
          + "\t\t\t\"#intellivtc2\": \"银行网点\"\n"
          + "\t\t},\n"
          + "\t\t\"tableIds\": {\n"
          + "\t\t\t\"#intellivtid1\": \"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\n"
          + "\t\t\t\"#intellivtid2\": \"47a69dfe-37ef-4ad1-aa19-1d61797a7821\"\n"
          + "\t\t},\n"
          + "\t\t\"tableSourceRel\": {},\n"
          + "\t\t\"codes\": {\n"
          + "\t\t\t\"#intellivtc1\": \"BankTreeViewVO\",\n"
          + "\t\t\t\"#intellivtc2\": \"BankDotVO\"\n"
          + "\t\t}\n"
          + "\t},\n"
          + "\t\"switchDataSource\": [],\n"
          + "\t\"obj\": {\n"
          + "\t\t\"name\": \"test019\",\n"
          + "\t\t\"code\": \"test019\",\n"
          + "\t\t\"reportType\": \"1\"\n"
          + "\t},\n"
          + "\t\"formulaObject\": {},\n"
          + "\t\"objId\": \"7694c998-debc-4f16-94fd-d11385b0b328\"\n"
          + "}";


  @Test
  public  void gsonSort2JsonSort() {

    jsonStr =
        "{\"model\":{\"_id\":{\"$oid\":\"60cb44860492b60059774cec\"},\"metaComponentId\":\"4d71ce1d-6211-4060-a19e-eeff9986a666\",\"dataRelation\":\"Join\",\"mul_language\":{\"zh_CN\":{},\"en_US\":{},\"zh_TW\":{}},\"description\":\"关联查询-条件参数过滤\",\"id\":\"7694c998-debc-4f16-94fd-d11385b0b328\",\"modelType\":\"Report\",\"metaType\":\"Class\",\"name\":\"test019\",\"displayName\":\"test019\",\"uri\":\"GT69287AT56.report.test019\",\"version\":1,\"tenantId\":\"edr19n2r\",\"ytenant_id\":\"edr19n2r\",\"metadataLevel\":\"2\",\"domain\":\"report\",\"status\":\"3\",\"ownedAttribute\":[{\"name\":\"modifier\",\"fieldName\":\"modifier\",\"displayName\":\"修改人\",\"type\":\"String\",\"length\":\"36\",\"id\":\"126fa209-3b07-4135-88e8-4badb61d794b\",\"uri\":\"bd.bank.BankTreeViewVO.modifier\",\"parentUri\":\"bd.bank.BankTreeViewVO\",\"nullable\":true,\"terms\":[],\"metaType\":\"Property\",\"modelType\":\"EntityAttrModel\",\"version\":13,\"dataType\":{\"id\":\"String\",\"name\":\"字符型\",\"uri\":\"String\",\"metaType\":\"PrimitiveType\"},\"key\":false,\"precise\":\"2\",\"isKey\":false,\"isNewDataName\":false,\"isNewDataCode\":false,\"is_mul_language\":false,\"isUnique\":false,\"_key\":\"126fa209-3b07-4135-88e8-4badb61d794b\",\"categoriesString\":\"\",\"mul_language_resid\":{\"displayName\":\"P_YS_PF_GZTORG_0000035173\"},\"code\":\"modifier\",\"metaClassId\":\"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\"oriName\":\"modifier\"},{\"fieldName\":\"dr\",\"key\":false,\"nullable\":false,\"length\":\"1\",\"precise\":\"2\",\"uri\":\"basedoc.basedocentity.BasedocBizObject.dr\",\"name\":\"dr\",\"displayName\":\"逻辑删除标记\",\"type\":\"Short\",\"id\":\"83e2fc3e-57e0-4ee1-a5fe-86c3d323dc58\",\"parentUri\":\"basedoc.basedocentity.BasedocBizObject\",\"terms\":[{\"_id\":{\"$oid\":\"5cdfa460dd026f004e51d025\"},\"code\":\"DRFLAG\",\"name\":\"删除标志\",\"description\":\"\",\"targetType\":\"PROPERTY\",\"id\":\"dea521fb-2e9c-4d96-8461-949a9b8121fa\",\"categories\":[{\"code\":\"specialAttr\",\"modifyTime\":\"2019-05-18 14:20:11:134\",\"createTime\":\"2019-05-18 14:20:11:134\",\"name\":\"特殊属性\",\"description\":\"\",\"_id\":{\"$oid\":\"5cdfa41bdd026f004e51d023\"},\"id\":\"9979b678-6613-45e7-bcc0-fb4ce330df4b\",\"parentId\":\"0\",\"mul_language\":{\"zh_TW\":{},\"en_US\":{},\"zh_CN\":{\"name\":\"特殊属性\"}}}],\"mul_language\":{\"zh_TW\":{},\"en_US\":{},\"zh_CN\":{\"name\":\"删除标志\"}},\"createTime\":\"2019-05-18 14:21:20:985\",\"modifyTime\":\"2019-05-18 14:22:04:363\",\"version\":1}],\"metaType\":\"Property\",\"modelType\":\"EntityAttrModel\",\"dataType\":{\"id\":\"Short\",\"name\":\"短整数\",\"uri\":\"Short\",\"metaType\":\"PrimitiveType\"},\"version\":12,\"defaultValue\":\"0\",\"isKey\":false,\"isNewDataName\":false,\"isNewDataCode\":false,\"_key\":\"83e2fc3e-57e0-4ee1-a5fe-86c3d323dc58\",\"categoriesString\":\"删除标志\",\"mul_language_resid\":{\"displayName\":\"P_YS_PF_GZTTMP_0000073434\"},\"code\":\"dr\",\"metaClassId\":\"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\"oriName\":\"dr\"},{\"name\":\"code\",\"fieldName\":\"code\",\"displayName\":\"编码\",\"type\":\"String\",\"length\":\"100\",\"id\":\"71f1489e-9182-4301-b41d-2bc33be896be\",\"uri\":\"bd.bank.BankDotVO.code\",\"parentUri\":\"bd.bank.BankDotVO\",\"nullable\":false,\"terms\":[{\"_id\":{\"$oid\":\"5d67abd803ff9c0060a9d3d0\"},\"code\":\"isCode\",\"name\":\"单据号\",\"description\":\"isCode\",\"targetType\":\"\",\"id\":\"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\"categories\":[{\"code\":\"flow\",\"modifyTime\":\"2020-06-13 14:47:44:975\",\"createTime\":\"2020-06-13 14:47:44:975\",\"name\":\"流程\",\"description\":\"\",\"_id\":{\"$oid\":\"5ee476902c5df9005fdd5ad4\"},\"id\":\"0f8c698f-d881-4a73-be89-5a95ee5ba391\",\"parentId\":\"0\",\"mul_language\":{\"zh_TW\":{},\"en_US\":{},\"zh_CN\":{\"name\":\"流程\"}}}],\"mul_language\":{\"zh_TW\":{},\"en_US\":{},\"zh_CN\":{\"name\":\"单据号\"}},\"createTime\":\"2019-08-29 18:41:28:693\",\"modifyTime\":\"2020-06-13 14:48:23:468\",\"version\":2,\"xmlTag\":\"isCode\",\"refpk\":\"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\"key\":\"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\"refcode\":\"isCode\",\"refname\":\"单据号\",\"memo\":\"isCode\"}],\"metaType\":\"Property\",\"modelType\":\"EntityAttrModel\",\"version\":21,\"dataType\":{\"id\":\"String\",\"name\":\"字符型\",\"uri\":\"String\",\"metaType\":\"PrimitiveType\"},\"isKey\":false,\"precise\":\"2\",\"isUnique\":true,\"isRequired\":true,\"createTime\":\"2019-09-04 17:30:52:458\",\"modifyTime\":\"2019-09-04 17:30:52:458\",\"_key\":\"71f1489e-9182-4301-b41d-2bc33be896be\",\"isNewDataName\":false,\"isNewDataCode\":false,\"is_mul_language\":false,\"mul_language_resid\":{\"displayName\":\"P_YS_FED_EXAMP_0000020286\"},\"categoriesString\":\"单据号\",\"key\":false,\"isCode\":true,\"code\":\"code\",\"metaClassId\":\"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\"oriName\":\"code\"},{\"displayName\":\"多语资源id\",\"name\":\"name_resid\",\"fieldName\":\"name_resid\",\"id\":\"b5ed8731-718f-40d7-981e-c78e6e7ba145\",\"isNewDataName\":false,\"isNewDataCode\":false,\"nullable\":\"true\",\"length\":256,\"dataType\":{\"name\":\"字符型\",\"id\":\"String\",\"metaType\":\"PrimitiveType\",\"uri\":\"String\"},\"precise\":\"2\",\"uri\":\"bd.bank.BankDotVO.name_resid\",\"tenantId\":\"sys\",\"metadataLevel\":\"0\",\"modelType\":\"EntityAttrModel\",\"metaType\":\"Property\",\"version\":4,\"createTime\":\"2020-05-13 09:48:17:067\",\"modifyTime\":\"2020-05-13 09:48:17:067\",\"terms\":[],\"_key\":\"b5ed8731-718f-40d7-981e-c78e6e7ba145\",\"categoriesString\":\"\",\"mul_language_resid\":{\"displayName\":\"P_YS_PF_METADATA_0001077410\"},\"is_mul_language\":false,\"code\":\"name_resid\",\"metaClassId\":\"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\"oriName\":\"name_resid\"},{\"name\":\"bank\",\"fieldName\":\"bank\",\"displayName\":\"社会级银行类别\",\"type\":\"String\",\"length\":\"36\",\"id\":\"276d84cb-245b-4db4-ad6d-b6498abe9f41\",\"uri\":\"bd.bank.BankTreeViewVO.bank\",\"parentUri\":\"bd.bank.BankTreeViewVO\",\"nullable\":true,\"terms\":[],\"metaType\":\"Property\",\"modelType\":\"EntityAttrModel\",\"version\":3,\"dataType\":{\"id\":\"String\",\"name\":\"字符型\",\"uri\":\"String\",\"metaType\":\"PrimitiveType\"},\"key\":false,\"precise\":\"2\",\"isKey\":false,\"isNewDataName\":false,\"isNewDataCode\":false,\"is_mul_language\":false,\"isUnique\":false,\"_key\":\"276d84cb-245b-4db4-ad6d-b6498abe9f41\",\"categoriesString\":\"\",\"mul_language_resid\":{\"displayName\":\"P_YS_PF_METADATA_0000084990\"},\"serialNumber\":210,\"code\":\"bank\",\"metaClassId\":\"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\"oriName\":\"bank\"}],\"createTime\":\"2021-06-21 10:24:42:927\",\"modifyTime\":\"2021-06-21 10:24:42:927\",\"oriFields\":[{\"name\":\"modifier\",\"tableCode\":\"BankTreeViewVO\",\"code\":\"modifier\",\"dataType\":\"String\"},{\"name\":\"dr\",\"tableCode\":\"BankTreeViewVO\",\"code\":\"dr\",\"dataType\":\"Short\"},{\"name\":\"code\",\"tableCode\":\"BankDotVO\",\"code\":\"code\",\"dataType\":\"String\"},{\"name\":\"name_resid\",\"tableCode\":\"BankDotVO\",\"code\":\"name_resid\"},{\"name\":\"bank\",\"tableCode\":\"BankTreeViewVO\",\"code\":\"bank\",\"dataType\":\"String\"}],\"operDefs\":[{\"operId\":\"126fa209-3b07-4135-88e8-4badb61d794b\",\"operType\":\"select\",\"code\":\"modifier\",\"name\":\"modifier\",\"paramaters\":{\"fieldCode\":\"modifier\",\"dataType\":\"String\",\"tableCode\":\"BankTreeViewVO\",\"fieldType\":\"DIMENSION\"},\"displayName\":\"修改人\",\"dataType\":{\"id\":\"String\",\"name\":\"字符型\",\"uri\":\"String\",\"metaType\":\"PrimitiveType\"},\"terms\":[],\"metaClassId\":\"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\"tableCode\":\"BankTreeViewVO\"},{\"operId\":\"83e2fc3e-57e0-4ee1-a5fe-86c3d323dc58\",\"operType\":\"select\",\"code\":\"dr\",\"name\":\"dr\",\"paramaters\":{\"fieldCode\":\"dr\",\"dataType\":\"Short\",\"tableCode\":\"BankTreeViewVO\",\"fieldType\":\"DIMENSION\"},\"displayName\":\"逻辑删除标记\",\"dataType\":{\"id\":\"Short\",\"name\":\"短整数\",\"uri\":\"Short\",\"metaType\":\"PrimitiveType\"},\"terms\":[{\"_id\":{\"$oid\":\"5cdfa460dd026f004e51d025\"},\"code\":\"DRFLAG\",\"name\":\"删除标志\",\"description\":\"\",\"targetType\":\"PROPERTY\",\"id\":\"dea521fb-2e9c-4d96-8461-949a9b8121fa\",\"categories\":[{\"code\":\"specialAttr\",\"modifyTime\":\"2019-05-18 14:20:11:134\",\"createTime\":\"2019-05-18 14:20:11:134\",\"name\":\"特殊属性\",\"description\":\"\",\"_id\":{\"$oid\":\"5cdfa41bdd026f004e51d023\"},\"id\":\"9979b678-6613-45e7-bcc0-fb4ce330df4b\",\"parentId\":\"0\",\"mul_language\":{\"zh_TW\":{},\"en_US\":{},\"zh_CN\":{\"name\":\"特殊属性\"}}}],\"mul_language\":{\"zh_TW\":{},\"en_US\":{},\"zh_CN\":{\"name\":\"删除标志\"}},\"createTime\":\"2019-05-18 14:21:20:985\",\"modifyTime\":\"2019-05-18 14:22:04:363\",\"version\":1}],\"metaClassId\":\"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\"tableCode\":\"BankTreeViewVO\"},{\"operId\":\"71f1489e-9182-4301-b41d-2bc33be896be\",\"operType\":\"select\",\"code\":\"code\",\"name\":\"code\",\"paramaters\":{\"fieldCode\":\"code\",\"dataType\":\"String\",\"tableCode\":\"BankDotVO\",\"fieldType\":\"DIMENSION\"},\"displayName\":\"编码\",\"dataType\":{\"id\":\"String\",\"name\":\"字符型\",\"uri\":\"String\",\"metaType\":\"PrimitiveType\"},\"terms\":[{\"_id\":{\"$oid\":\"5d67abd803ff9c0060a9d3d0\"},\"code\":\"isCode\",\"name\":\"单据号\",\"description\":\"isCode\",\"targetType\":\"\",\"id\":\"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\"categories\":[{\"code\":\"flow\",\"modifyTime\":\"2020-06-13 14:47:44:975\",\"createTime\":\"2020-06-13 14:47:44:975\",\"name\":\"流程\",\"description\":\"\",\"_id\":{\"$oid\":\"5ee476902c5df9005fdd5ad4\"},\"id\":\"0f8c698f-d881-4a73-be89-5a95ee5ba391\",\"parentId\":\"0\",\"mul_language\":{\"zh_TW\":{},\"en_US\":{},\"zh_CN\":{\"name\":\"流程\"}}}],\"mul_language\":{\"zh_TW\":{},\"en_US\":{},\"zh_CN\":{\"name\":\"单据号\"}},\"createTime\":\"2019-08-29 18:41:28:693\",\"modifyTime\":\"2020-06-13 14:48:23:468\",\"version\":2,\"xmlTag\":\"isCode\",\"refpk\":\"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\"key\":\"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\"refcode\":\"isCode\",\"refname\":\"单据号\",\"memo\":\"isCode\"}],\"metaClassId\":\"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\"tableCode\":\"BankDotVO\"},{\"operId\":\"b5ed8731-718f-40d7-981e-c78e6e7ba145\",\"operType\":\"select\",\"code\":\"name_resid\",\"name\":\"name_resid\",\"paramaters\":{\"fieldCode\":\"name_resid\",\"tableCode\":\"BankDotVO\",\"fieldType\":\"DIMENSION\"},\"displayName\":\"多语资源id\",\"dataType\":{\"name\":\"字符型\",\"id\":\"String\",\"metaType\":\"PrimitiveType\",\"uri\":\"String\"},\"terms\":[],\"metaClassId\":\"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\"tableCode\":\"BankDotVO\"},{\"operId\":\"276d84cb-245b-4db4-ad6d-b6498abe9f41\",\"operType\":\"select\",\"code\":\"bank\",\"name\":\"bank\",\"paramaters\":{\"fieldCode\":\"bank\",\"dataType\":\"String\",\"tableCode\":\"BankTreeViewVO\",\"fieldType\":\"DIMENSION\"},\"displayName\":\"社会级银行类别\",\"dataType\":{\"id\":\"String\",\"name\":\"字符型\",\"uri\":\"String\",\"metaType\":\"PrimitiveType\"},\"terms\":[],\"metaClassId\":\"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\"tableCode\":\"BankTreeViewVO\"}],\"fileds\":[{\"name\":\"modifier\",\"fieldName\":\"modifier\",\"displayName\":\"修改人\",\"type\":\"String\",\"length\":\"36\",\"id\":\"126fa209-3b07-4135-88e8-4badb61d794b\",\"uri\":\"bd.bank.BankTreeViewVO.modifier\",\"parentUri\":\"bd.bank.BankTreeViewVO\",\"nullable\":true,\"terms\":[],\"metaType\":\"Property\",\"modelType\":\"EntityAttrModel\",\"version\":13,\"dataType\":{\"id\":\"String\",\"name\":\"字符型\",\"uri\":\"String\",\"metaType\":\"PrimitiveType\"},\"key\":false,\"precise\":\"2\",\"isKey\":false,\"isNewDataName\":false,\"isNewDataCode\":false,\"is_mul_language\":false,\"isUnique\":false,\"_key\":\"126fa209-3b07-4135-88e8-4badb61d794b\",\"categoriesString\":\"\",\"mul_language_resid\":{\"displayName\":\"P_YS_PF_GZTORG_0000035173\"},\"code\":\"modifier\",\"metaClassId\":\"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\"oriName\":\"modifier\"},{\"fieldName\":\"dr\",\"key\":false,\"nullable\":false,\"length\":\"1\",\"precise\":\"2\",\"uri\":\"basedoc.basedocentity.BasedocBizObject.dr\",\"name\":\"dr\",\"displayName\":\"逻辑删除标记\",\"type\":\"Short\",\"id\":\"83e2fc3e-57e0-4ee1-a5fe-86c3d323dc58\",\"parentUri\":\"basedoc.basedocentity.BasedocBizObject\",\"terms\":[{\"_id\":{\"$oid\":\"5cdfa460dd026f004e51d025\"},\"code\":\"DRFLAG\",\"name\":\"删除标志\",\"description\":\"\",\"targetType\":\"PROPERTY\",\"id\":\"dea521fb-2e9c-4d96-8461-949a9b8121fa\",\"categories\":[{\"code\":\"specialAttr\",\"modifyTime\":\"2019-05-18 14:20:11:134\",\"createTime\":\"2019-05-18 14:20:11:134\",\"name\":\"特殊属性\",\"description\":\"\",\"_id\":{\"$oid\":\"5cdfa41bdd026f004e51d023\"},\"id\":\"9979b678-6613-45e7-bcc0-fb4ce330df4b\",\"parentId\":\"0\",\"mul_language\":{\"zh_TW\":{},\"en_US\":{},\"zh_CN\":{\"name\":\"特殊属性\"}}}],\"mul_language\":{\"zh_TW\":{},\"en_US\":{},\"zh_CN\":{\"name\":\"删除标志\"}},\"createTime\":\"2019-05-18 14:21:20:985\",\"modifyTime\":\"2019-05-18 14:22:04:363\",\"version\":1}],\"metaType\":\"Property\",\"modelType\":\"EntityAttrModel\",\"dataType\":{\"id\":\"Short\",\"name\":\"短整数\",\"uri\":\"Short\",\"metaType\":\"PrimitiveType\"},\"version\":12,\"defaultValue\":\"0\",\"isKey\":false,\"isNewDataName\":false,\"isNewDataCode\":false,\"_key\":\"83e2fc3e-57e0-4ee1-a5fe-86c3d323dc58\",\"categoriesString\":\"删除标志\",\"mul_language_resid\":{\"displayName\":\"P_YS_PF_GZTTMP_0000073434\"},\"code\":\"dr\",\"metaClassId\":\"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\"oriName\":\"dr\"},{\"name\":\"code\",\"fieldName\":\"code\",\"displayName\":\"编码\",\"type\":\"String\",\"length\":\"100\",\"id\":\"71f1489e-9182-4301-b41d-2bc33be896be\",\"uri\":\"bd.bank.BankDotVO.code\",\"parentUri\":\"bd.bank.BankDotVO\",\"nullable\":false,\"terms\":[{\"_id\":{\"$oid\":\"5d67abd803ff9c0060a9d3d0\"},\"code\":\"isCode\",\"name\":\"单据号\",\"description\":\"isCode\",\"targetType\":\"\",\"id\":\"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\"categories\":[{\"code\":\"flow\",\"modifyTime\":\"2020-06-13 14:47:44:975\",\"createTime\":\"2020-06-13 14:47:44:975\",\"name\":\"流程\",\"description\":\"\",\"_id\":{\"$oid\":\"5ee476902c5df9005fdd5ad4\"},\"id\":\"0f8c698f-d881-4a73-be89-5a95ee5ba391\",\"parentId\":\"0\",\"mul_language\":{\"zh_TW\":{},\"en_US\":{},\"zh_CN\":{\"name\":\"流程\"}}}],\"mul_language\":{\"zh_TW\":{},\"en_US\":{},\"zh_CN\":{\"name\":\"单据号\"}},\"createTime\":\"2019-08-29 18:41:28:693\",\"modifyTime\":\"2020-06-13 14:48:23:468\",\"version\":2,\"xmlTag\":\"isCode\",\"refpk\":\"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\"key\":\"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\"refcode\":\"isCode\",\"refname\":\"单据号\",\"memo\":\"isCode\"}],\"metaType\":\"Property\",\"modelType\":\"EntityAttrModel\",\"version\":21,\"dataType\":{\"id\":\"String\",\"name\":\"字符型\",\"uri\":\"String\",\"metaType\":\"PrimitiveType\"},\"isKey\":false,\"precise\":\"2\",\"isUnique\":true,\"isRequired\":true,\"createTime\":\"2019-09-04 17:30:52:458\",\"modifyTime\":\"2019-09-04 17:30:52:458\",\"_key\":\"71f1489e-9182-4301-b41d-2bc33be896be\",\"isNewDataName\":false,\"isNewDataCode\":false,\"is_mul_language\":false,\"mul_language_resid\":{\"displayName\":\"P_YS_FED_EXAMP_0000020286\"},\"categoriesString\":\"单据号\",\"key\":false,\"isCode\":true,\"code\":\"code\",\"metaClassId\":\"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\"oriName\":\"code\"},{\"displayName\":\"多语资源id\",\"name\":\"name_resid\",\"fieldName\":\"name_resid\",\"id\":\"b5ed8731-718f-40d7-981e-c78e6e7ba145\",\"isNewDataName\":false,\"isNewDataCode\":false,\"nullable\":\"true\",\"length\":256,\"dataType\":{\"name\":\"字符型\",\"id\":\"String\",\"metaType\":\"PrimitiveType\",\"uri\":\"String\"},\"precise\":\"2\",\"uri\":\"bd.bank.BankDotVO.name_resid\",\"tenantId\":\"sys\",\"metadataLevel\":\"0\",\"modelType\":\"EntityAttrModel\",\"metaType\":\"Property\",\"version\":4,\"createTime\":\"2020-05-13 09:48:17:067\",\"modifyTime\":\"2020-05-13 09:48:17:067\",\"terms\":[],\"_key\":\"b5ed8731-718f-40d7-981e-c78e6e7ba145\",\"categoriesString\":\"\",\"mul_language_resid\":{\"displayName\":\"P_YS_PF_METADATA_0001077410\"},\"is_mul_language\":false,\"code\":\"name_resid\",\"metaClassId\":\"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\"oriName\":\"name_resid\"},{\"name\":\"bank\",\"fieldName\":\"bank\",\"displayName\":\"社会级银行类别\",\"type\":\"String\",\"length\":\"36\",\"id\":\"276d84cb-245b-4db4-ad6d-b6498abe9f41\",\"uri\":\"bd.bank.BankTreeViewVO.bank\",\"parentUri\":\"bd.bank.BankTreeViewVO\",\"nullable\":true,\"terms\":[],\"metaType\":\"Property\",\"modelType\":\"EntityAttrModel\",\"version\":3,\"dataType\":{\"id\":\"String\",\"name\":\"字符型\",\"uri\":\"String\",\"metaType\":\"PrimitiveType\"},\"key\":false,\"precise\":\"2\",\"isKey\":false,\"isNewDataName\":false,\"isNewDataCode\":false,\"is_mul_language\":false,\"isUnique\":false,\"_key\":\"276d84cb-245b-4db4-ad6d-b6498abe9f41\",\"categoriesString\":\"\",\"mul_language_resid\":{\"displayName\":\"P_YS_PF_METADATA_0000084990\"},\"serialNumber\":210,\"code\":\"bank\",\"metaClassId\":\"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\"oriName\":\"bank\"}],\"joinGeneral\":{\"general\":[{\"id\":\"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\"objID\":\"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\"objName\":\"银行类别\",\"objTable\":\"银行类别\",\"objComment\":\"银行类别\",\"objCode\":\"BankTreeViewVO\",\"objType\":29,\"includeTenant\":true,\"parentId\":\"\",\"x\":50,\"y\":138},{\"id\":\"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\"objID\":\"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\"objName\":\"银行网点\",\"objTable\":\"银行网点\",\"objComment\":\"银行网点\",\"objCode\":\"BankDotVO\",\"objType\":29,\"includeTenant\":true,\"parentId\":\"\",\"x\":598,\"y\":144}],\"links\":[{\"dataRelation\":\"Join\",\"linkType\":\"InnerJoin\",\"leftKey\":\"name\",\"rightKey\":\"sysid\",\"leftObjName\":\"银行类别\",\"rightObjName\":\"银行网点\",\"leftObjType\":29,\"rightObjType\":29,\"linkItems\":[{\"leftFieldCode\":\"name\",\"leftFieldType\":\"String\",\"leftFieldFunc\":\"\",\"rightFieldCode\":\"sysid\",\"rightFieldType\":\"String\",\"rightFieldFunc\":\"\"}],\"leftFieldType\":\"String\",\"rightFieldType\":\"String\"}]},\"links\":[{\"dataRelation\":\"Join\",\"linkType\":\"InnerJoin\",\"leftKey\":\"name\",\"rightKey\":\"sysid\",\"leftObjName\":\"bd.bank.BankTreeViewVO\",\"rightObjName\":\"bd.bank.BankDotVO\",\"leftObjType\":29,\"rightObjType\":29,\"linkItems\":[{\"leftFieldCode\":\"name\",\"leftFieldType\":\"String\",\"leftFieldFunc\":\"\",\"rightFieldCode\":\"sysid\",\"rightFieldType\":\"String\",\"rightFieldFunc\":\"\"}],\"leftFieldType\":\"String\",\"rightFieldType\":\"String\",\"leftObjId\":\"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\"rightObjId\":\"47a69dfe-37ef-4ad1-aa19-1d61797a7821\"}],\"info\":{\"dataSource\":{},\"tableCodes\":{\"#intellivtc1\":\"银行类别\",\"#intellivtc2\":\"银行网点\"},\"tableIds\":{\"#intellivtid1\":\"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\"#intellivtid2\":\"47a69dfe-37ef-4ad1-aa19-1d61797a7821\"},\"tableSourceRel\":{},\"codes\":{\"#intellivtc1\":\"BankTreeViewVO\",\"#intellivtc2\":\"BankDotVO\"}},\"obj\":{\"name\":\"test019\",\"code\":\"test019\",\"reportType\":\"1\"},\"querySchema\":{\"fields\":[{\"name\":\"modifier\",\"fieldName\":\"modifier\",\"displayName\":\"修改人\",\"type\":\"String\",\"length\":\"36\",\"id\":\"126fa209-3b07-4135-88e8-4badb61d794b\",\"uri\":\"bd.bank.BankTreeViewVO.modifier\",\"parentUri\":\"bd.bank.BankTreeViewVO\",\"nullable\":true,\"terms\":[],\"metaType\":\"Property\",\"modelType\":\"EntityAttrModel\",\"version\":13,\"dataType\":{\"id\":\"String\",\"name\":\"字符型\",\"uri\":\"String\",\"metaType\":\"PrimitiveType\"},\"key\":false,\"precise\":\"2\",\"isKey\":false,\"isNewDataName\":false,\"isNewDataCode\":false,\"is_mul_language\":false,\"isUnique\":false,\"_key\":\"126fa209-3b07-4135-88e8-4badb61d794b\",\"categoriesString\":\"\",\"mul_language_resid\":{\"displayName\":\"P_YS_PF_GZTORG_0000035173\"},\"code\":\"modifier\",\"metaClassId\":\"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\"oriName\":\"modifier\"},{\"fieldName\":\"dr\",\"key\":false,\"nullable\":false,\"length\":\"1\",\"precise\":\"2\",\"uri\":\"basedoc.basedocentity.BasedocBizObject.dr\",\"name\":\"dr\",\"displayName\":\"逻辑删除标记\",\"type\":\"Short\",\"id\":\"83e2fc3e-57e0-4ee1-a5fe-86c3d323dc58\",\"parentUri\":\"basedoc.basedocentity.BasedocBizObject\",\"terms\":[{\"_id\":{\"$oid\":\"5cdfa460dd026f004e51d025\"},\"code\":\"DRFLAG\",\"name\":\"删除标志\",\"description\":\"\",\"targetType\":\"PROPERTY\",\"id\":\"dea521fb-2e9c-4d96-8461-949a9b8121fa\",\"categories\":[{\"code\":\"specialAttr\",\"modifyTime\":\"2019-05-18 14:20:11:134\",\"createTime\":\"2019-05-18 14:20:11:134\",\"name\":\"特殊属性\",\"description\":\"\",\"_id\":{\"$oid\":\"5cdfa41bdd026f004e51d023\"},\"id\":\"9979b678-6613-45e7-bcc0-fb4ce330df4b\",\"parentId\":\"0\",\"mul_language\":{\"zh_TW\":{},\"en_US\":{},\"zh_CN\":{\"name\":\"特殊属性\"}}}],\"mul_language\":{\"zh_TW\":{},\"en_US\":{},\"zh_CN\":{\"name\":\"删除标志\"}},\"createTime\":\"2019-05-18 14:21:20:985\",\"modifyTime\":\"2019-05-18 14:22:04:363\",\"version\":1}],\"metaType\":\"Property\",\"modelType\":\"EntityAttrModel\",\"dataType\":{\"id\":\"Short\",\"name\":\"短整数\",\"uri\":\"Short\",\"metaType\":\"PrimitiveType\"},\"version\":12,\"defaultValue\":\"0\",\"isKey\":false,\"isNewDataName\":false,\"isNewDataCode\":false,\"_key\":\"83e2fc3e-57e0-4ee1-a5fe-86c3d323dc58\",\"categoriesString\":\"删除标志\",\"mul_language_resid\":{\"displayName\":\"P_YS_PF_GZTTMP_0000073434\"},\"code\":\"dr\",\"metaClassId\":\"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\"oriName\":\"dr\"},{\"name\":\"code\",\"fieldName\":\"code\",\"displayName\":\"编码\",\"type\":\"String\",\"length\":\"100\",\"id\":\"71f1489e-9182-4301-b41d-2bc33be896be\",\"uri\":\"bd.bank.BankDotVO.code\",\"parentUri\":\"bd.bank.BankDotVO\",\"nullable\":false,\"terms\":[{\"_id\":{\"$oid\":\"5d67abd803ff9c0060a9d3d0\"},\"code\":\"isCode\",\"name\":\"单据号\",\"description\":\"isCode\",\"targetType\":\"\",\"id\":\"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\"categories\":[{\"code\":\"flow\",\"modifyTime\":\"2020-06-13 14:47:44:975\",\"createTime\":\"2020-06-13 14:47:44:975\",\"name\":\"流程\",\"description\":\"\",\"_id\":{\"$oid\":\"5ee476902c5df9005fdd5ad4\"},\"id\":\"0f8c698f-d881-4a73-be89-5a95ee5ba391\",\"parentId\":\"0\",\"mul_language\":{\"zh_TW\":{},\"en_US\":{},\"zh_CN\":{\"name\":\"流程\"}}}],\"mul_language\":{\"zh_TW\":{},\"en_US\":{},\"zh_CN\":{\"name\":\"单据号\"}},\"createTime\":\"2019-08-29 18:41:28:693\",\"modifyTime\":\"2020-06-13 14:48:23:468\",\"version\":2,\"xmlTag\":\"isCode\",\"refpk\":\"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\"key\":\"b92cb8fe-83ae-46c4-9fe9-926b7ac1f822\",\"refcode\":\"isCode\",\"refname\":\"单据号\",\"memo\":\"isCode\"}],\"metaType\":\"Property\",\"modelType\":\"EntityAttrModel\",\"version\":21,\"dataType\":{\"id\":\"String\",\"name\":\"字符型\",\"uri\":\"String\",\"metaType\":\"PrimitiveType\"},\"isKey\":false,\"precise\":\"2\",\"isUnique\":true,\"isRequired\":true,\"createTime\":\"2019-09-04 17:30:52:458\",\"modifyTime\":\"2019-09-04 17:30:52:458\",\"_key\":\"71f1489e-9182-4301-b41d-2bc33be896be\",\"isNewDataName\":false,\"isNewDataCode\":false,\"is_mul_language\":false,\"mul_language_resid\":{\"displayName\":\"P_YS_FED_EXAMP_0000020286\"},\"categoriesString\":\"单据号\",\"key\":false,\"isCode\":true,\"code\":\"code\",\"metaClassId\":\"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\"oriName\":\"code\"},{\"displayName\":\"多语资源id\",\"name\":\"name_resid\",\"fieldName\":\"name_resid\",\"id\":\"b5ed8731-718f-40d7-981e-c78e6e7ba145\",\"isNewDataName\":false,\"isNewDataCode\":false,\"nullable\":\"true\",\"length\":256,\"dataType\":{\"name\":\"字符型\",\"id\":\"String\",\"metaType\":\"PrimitiveType\",\"uri\":\"String\"},\"precise\":\"2\",\"uri\":\"bd.bank.BankDotVO.name_resid\",\"tenantId\":\"sys\",\"metadataLevel\":\"0\",\"modelType\":\"EntityAttrModel\",\"metaType\":\"Property\",\"version\":4,\"createTime\":\"2020-05-13 09:48:17:067\",\"modifyTime\":\"2020-05-13 09:48:17:067\",\"terms\":[],\"_key\":\"b5ed8731-718f-40d7-981e-c78e6e7ba145\",\"categoriesString\":\"\",\"mul_language_resid\":{\"displayName\":\"P_YS_PF_METADATA_0001077410\"},\"is_mul_language\":false,\"code\":\"name_resid\",\"metaClassId\":\"47a69dfe-37ef-4ad1-aa19-1d61797a7821\",\"oriName\":\"name_resid\"},{\"name\":\"bank\",\"fieldName\":\"bank\",\"displayName\":\"社会级银行类别\",\"type\":\"String\",\"length\":\"36\",\"id\":\"276d84cb-245b-4db4-ad6d-b6498abe9f41\",\"uri\":\"bd.bank.BankTreeViewVO.bank\",\"parentUri\":\"bd.bank.BankTreeViewVO\",\"nullable\":true,\"terms\":[],\"metaType\":\"Property\",\"modelType\":\"EntityAttrModel\",\"version\":3,\"dataType\":{\"id\":\"String\",\"name\":\"字符型\",\"uri\":\"String\",\"metaType\":\"PrimitiveType\"},\"key\":false,\"precise\":\"2\",\"isKey\":false,\"isNewDataName\":false,\"isNewDataCode\":false,\"is_mul_language\":false,\"isUnique\":false,\"_key\":\"276d84cb-245b-4db4-ad6d-b6498abe9f41\",\"categoriesString\":\"\",\"mul_language_resid\":{\"displayName\":\"P_YS_PF_METADATA_0000084990\"},\"serialNumber\":210,\"code\":\"bank\",\"metaClassId\":\"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\"oriName\":\"bank\"}],\"pager\":{\"pageIndex\":\"1\",\"pageSize\":\"10\"},\"conditions\":[]},\"paramList\":[],\"fieldSeqs\":[\"modifier\",\"dr\",\"code\",\"name_resid\",\"bank\"]},\"info\":{\"dataSource\":{},\"tableCodes\":{\"#intellivtc1\":\"银行类别\",\"#intellivtc2\":\"银行网点\"},\"tableIds\":{\"#intellivtid1\":\"ba8ee4e0-1162-443f-9c48-4411cb6041b2\",\"#intellivtid2\":\"47a69dfe-37ef-4ad1-aa19-1d61797a7821\"},\"tableSourceRel\":{},\"codes\":{\"#intellivtc1\":\"BankTreeViewVO\",\"#intellivtc2\":\"BankDotVO\"}},\"switchDataSource\":[],\"obj\":{\"name\":\"test019\",\"code\":\"test019\",\"reportType\":\"1\"},\"formulaObject\":{},\"objId\":\"7694c998-debc-4f16-94fd-d11385b0b328\"}";

    JsonParser jsonParser = new JsonParser();
    JsonObject reportJsonObj = (JsonObject) jsonParser.parse(jsonStr);

    //JsonArray ownedAttribute = JsonObjectUtils.getJsonArray(reportJsonObj, "ownedAttribute");
    JsonObject model = reportJsonObj.get("model").getAsJsonObject();

    JsonArray ownedAttribute = model.get("ownedAttribute").getAsJsonArray();

    String ownedAttributesStr = ownedAttribute.toString();
    JSONArray ownedAttributeArray =
        (JSONArray) JSONObject.parse(ownedAttributesStr, Feature.OrderedField);
    log.info(
        "\n排序前:"
            + "\n===============================================\n"
            + "{}"
            + "\n===============================================",
        JSONArray.toJSONString(ownedAttributeArray, true));

    // 排序: 按code字母顺序-默认大写优先
    // ownedAttributeArray.sort(Comparator.comparing(json -> ((JSONObject)
    // json).getString("name")));
    // 排序: 按code字母顺序-忽略大小写
    ownedAttributeArray.sort(
        (a, b) ->
            ((JSONObject) a)
                .getString("name")
                .compareToIgnoreCase(((JSONObject) b).getString("name")));

    log.info(
        "\n排序后,sort by name:"
            + "\n===============================================\n"
            + "{}"
            + "\n===============================================",
        JSONArray.toJSONString(ownedAttributeArray, true));


    String s = JSONArray.toJSONString(ownedAttributeArray);
    JsonArray asJsonArray = jsonParser.parse(s).getAsJsonArray();


    JSONArray asJsonArray_fast =
            (JSONArray) JSONObject.parse(asJsonArray.toString(), Feature.OrderedField);
    log.info(
            "\n排序前:"
                    + "\n===============================================\n"
                    + "{}"
                    + "\n===============================================",
            JSONArray.toJSONString(asJsonArray_fast, true));

  }
}
