DROP TABLE IF EXISTS user;

CREATE TABLE user
(
    id           BIGINT(20) NOT NULL COMMENT '主键ID' AUTO_INCREMENT,
    name         VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    age          INT(11) NULL DEFAULT NULL COMMENT '年龄',
    email        VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    user_friends VARCHAR(50) NULL DEFAULT NULL COMMENT '朋友',
    PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


DROP TABLE IF EXISTS user2;
CREATE TABLE user2
(
    id           BIGINT(20) NOT NULL COMMENT '主键ID' AUTO_INCREMENT,
    name         VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    age          INT(11) NULL DEFAULT NULL COMMENT '年龄',
    email        VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    user_friends VARCHAR(50) NULL DEFAULT NULL COMMENT '朋友',
    PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;