package com.st.utils.collection;

import com.alibaba.fastjson.JSONObject;
import com.google.common.collect.Maps;
import com.st.utils.log.LogUtils;
import lombok.extern.slf4j.Slf4j;

import java.util.HashMap;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * @author: st
 * @date: 2021/12/8 15:53
 * @version: 1.0
 * @description:
 */
@Slf4j
public class MapUtil {

  /**
   * 合并两个 {@link Map<String,String>}<p></p>
   *
   * 合并两个Map, 如果两个map有相同的key, 则后面的map将会覆盖前面的map
   *
   * <pre>
   *    // 如果key相同, 则map2的value会覆盖 map1的value
   *    result.putAll(map1);
   *    result.putAll(map2);
   * </pre>
   *
   * @param map1
   * @param map2
   * @return 合并后的map
   */
  public static Map<String, String> mergeMaps(Map<String, String> map1, Map<String, String> map2) {
    HashMap<String, String> result = Maps.newHashMap();
    result.putAll(map1);
    result.putAll(map2);

    return result;
  }

  public void  putall(){
    HashMap<String, String> m1;
    HashMap<String, String> m2;

    String s1 =
        "{\"uorder\":\"uorders\",\"IMP-EMS\":\"imp_ems\",\"scmmp\":\"scmmp\",\"ucf-amc-ambd\":\"amc_ambd\",\"ctm-cmp\":\"ctmcmp\",\"marketingbill\":\"uorders\",\"PLM-PLM-PSDM\":\"imp_plm\",\"znbzbx\":\"shared_service\",\"membercenter\":\"yilian\",\"MDDHR\":\"hrcloud\",\"HR\":\"hrcloud\",\"sact\":\"sact\",\"QMS-DFM\":\"qms_dfm\",\"system2\":\"systemSchema2\",\"system1\":\"systemSchema1\",\"system3\":\"systemSchema3\",\"sy0001\":\"isv_builder\",\"requirementsplanning\":\"requirements_planning\",\"sharedservicecenter\":\"shared_service\",\"ucf-staff-center\":\"iuap_cloud_basedoc\",\"transtype\":\"iuap_cloud_basedoc\",\"mall\":\"upmalls\",\"hrcloud-talent\":\"hrcloud\",\"ucf-org-center\":\"iuap_cloud_basedoc\",\"umall\":\"upmalls\",\"productcenter\":\"ugoods\",\"productionorder\":\"production_order\",\"MDDHRPUB\":\"hrcloud\",\"imp-pes\":\"imp_pes_prod\",\"znbz\":\"shared_service\",\"yssupplier\":\"ugoods\",\"upu\":\"upurchase\",\"ucf-amc-aom\":\"amc_aom\",\"IMP-BASE\":\"imp_plm\",\"ucfbasedoc\":\"iuap_cloud_basedoc\",\"finbd\":\"fiproduct\",\"QMS-QIT\":\"qms_qit\",\"dst\":\"omsdata\",\"uhy\":\"yilian\",\"PLM-PLM-PBS\":\"imp_plm\",\"ucf-amc-rmm\":\"amc_mro\",\"engineeringdata\":\"engineering_data\",\"retail\":\"uretaildata\",\"uinttrade\":\"uinttrade\",\"IMP-PES\":\"imp_pes_prod\",\"yonyoufi\":\"fiproduct\",\"yycrm\":\"crm\",\"IMP-PLM-PSDM\":\"imp_plm\",\"hrcloud-wa\":\"hrcloud\",\"developplatform\":\"code_20200630\",\"yxybase\":\"pricecenter\",\"ucf-amc-aum\":\"amc_aum\",\"udinghuo\":\"uorders\",\"IMP-SCS\":\"imp_plm\",\"ustock\":\"ustock\",\"hrcloud-attend\":\"hrcloud\",\"IMP-HSE\":\"imp_hse\",\"IMP-PLM-WIDGET\":\"imp_plm\",\"ucf-amc-aim\":\"amc_aim\",\"hrcloud-talent-basedoc\":\"iuap_cloud_basedoc\",\"IMP-DFM-EMS\":\"imp_ems\",\"IMP-GDS\":\"imp_plm\"}";

    m1 = (HashMap<String, String>) JSONObject.parseObject(s1, Map.class);
    LogUtils.foal(m1,"");

    String s2 =
        "{\n"
            + "\"domain.yonbip-am-aum\":\"https://yonbip.diwork.com/yonbip-am-aum\",\n"
            + "\"domain.iuap-apcom-messageplatform\":\"https://yonbip.diwork.com/iuap-apcom-messageplatform\",\n"
            + "\"elastic.password\":\"kdFQrYwn^o9cy360\",\n"
            + "\"domain.yonbip-fi-sepmbcdc\":\"https://yonbip.diwork.com/yonbip-fi-sepmbcdc\",\n"
            + "\"domain.yonbip-hr-attendsign\":\"https://yonbip.diwork.com/yonbip-hr-attendsign\",\n"
            + "\"domain.yonbip-mm-plmrd\":\"https://yonbip.diwork.com/yonbip-mm-plmrd\",\n"
            + "\"domain.yonbip-fi-report\":\"https://yonbip.diwork.com/yonbip-fi-report\",\n"
            + "\"domain.yonbip-ec-php-api-rest-h5\":\"https://yonbip.diwork.com/yonbip-ec-php-api-rest/h5-api\",\n"
            + "\"domain.yonbip-fi-expsrbsm\":\"https://yonbip.diwork.com/yonbip-fi-expsrbsm\",\n"
            + "\"domain.yonbip-cpu-bcsupervision\":\"https://yonbip.diwork.com/yonbip-cpu-bcsupervision\",\n"
            + "\"domain.iuap-mdf-node\":\"https://yonbip.diwork.com/mdf-node\",\n"
            + "\"domain.yonbip-hr-staffproc\":\"https://yonbip.diwork.com/yonbip-hr-staffproc\",\n"
            + "\"domain.yonbip-am-rmm\":\"https://yonbip.diwork.com/yonbip-am-rmm\",\n"
            + "\"issimpleregister\":\"0\",\n"
            + "\"domain.iuap-apdoc-customer\":\"https://yonbip.diwork.com/iuap-apdoc-customer\",\n"
            + "\"force_disable_translate\":\"false\",\n"
            + "\"mdd_schema.ucf-amc-aim\":\"amc_aim\",\n"
            + "\"domain.iuap-apdoc-social\":\"https://yonbip.diwork.com/iuap-apdoc-social\",\n"
            + "\"user.dir\":\"/app\",\n"
            + "\"UAP.RandomAlgorithm\":\"SHA1PRNG\",\n"
            + "\"java.vm.version\":\"25.202-b08\",\n"
            + "\"domain.yonbip-mm-qic\":\"https://yonbip.diwork.com/yonbip-mm-qic\",\n"
            + "\"domain.iuap-data-ep\":\"https://yonbip.diwork.com/iuap-data-ep\",\n"
            + "\"mdd_schema.yxybase\":\"pricecenter\",\n"
            + "\"domain.yonbip-ec-portal\":\"https://yonbip.diwork.com/yonbip-ec-portal\",\n"
            + "\"domain.yonbip-mid-sscpf\":\"https://yonbip.diwork.com/yonbip-mid-sscpf\",\n"
            + "\"domain.yonbip-fi-otp\":\"https://yonbip.diwork.com/yonbip-fi-otp\",\n"
            + "\"oauth2file.path\":\"oauth2.properties\",\n"
            + "\"domain.yonbip-cpu-cooperation\":\"https://yonbip.diwork.com/yonbip-cpu-cooperation\",\n"
            + "\"domain.iuap-ipaas-hybridcloudHub\":\"https://yonbip.diwork.com/iuap-ipaas-hybridcloudHub\",\n"
            + "\"domain.yonbip-fi-miderp\":\"https://yonbip.diwork.com/yonbip-fi-miderp\",\n"
            + "\"mdd_schema.uinttrade\":\"uinttrade\",\n"
            + "\"domain.yonbip-cpu-file\":\"https://yonbip.diwork.com/yonbip-cpu-file\",\n"
            + "\"primary.access.key\":\"primary.access.key\",\n"
            + "\"mdd_schema.ustock\":\"ustock\",\n"
            + "\"domain.iuap-yonbuilder-runtime\":\"https://yonbip.diwork.com/iuap-yonbuilder-runtime\",\n"
            + "\"sun.os.patch.level\":\"unknown\",\n"
            + "\"A69.version\":\"1.0\",\n"
            + "\"domain.yonbip-mkt-mkc2breport\":\"https://yonbip.diwork.com/yonbip-mkt-mkc2breport\",\n"
            + "\"ucf.search.token.default\":\"3xma418Or9uk417derohzy2k2UQ=\",\n"
            + "\"domain.yonbip-mm-plmpd\":\"https://yonbip.diwork.com/yonbip-mm-plmpd\",\n"
            + "\"java.vm.specification.name\":\"Java Virtual Machine Specification\",\n"
            + "\"mdd_schema.znbzbx\":\"znbz\",\n"
            + "\"elastic.cluster.name\":\"es\",\n"
            + "\"mdd_schema.hrcloud-wa\":\"hrcloud\",\n"
            + "\"domain.yonbip-ec-collaboration\":\"https://yonbip.diwork.com/yonbip-ec-collaboration\",\n"
            + "\"domain.iuap-api-management\":\"https://yonbip.diwork.com/iuap-api-management\",\n"
            + "\"domain.yonbip-fi-eaai\":\"https://yonbip.diwork.com/yonbip-fi-eaai\",\n"
            + "\"domain.yonbip-hr-trainbiz\":\"https://yonbip.diwork.com/yonbip-hr-trainbiz\",\n"
            + "\"domain.yonbip-mm-ehs\":\"https://yonbip.diwork.com/yonbip-mm-ehs\",\n"
            + "\"A69.base_path\":\"../\",\n"
            + "\"domain.iuap-apcom-prewarning\":\"https://yonbip.diwork.com/iuap-apcom-prewarning\",\n"
            + "\"domain.yonbip-mm-mfmr\":\"https://yonbip.diwork.com/yonbip-mm-mfmr\",\n"
            + "\"domain.iuap-00-apilink\":\"https://yonbip.diwork.com/iuap-00-apilink\",\n"
            + "\"domain.yonbip-mkt-dinghuo\":\"https://yonbip.diwork.com/yonbip-mkt-dinghuo\",\n"
            + "\"domain.iuap-apcom-print\":\"https://yonbip.diwork.com/iuap-apcom-print\",\n"
            + "\"domain.yonbip-cpu-bctask\":\"https://yonbip.diwork.com/yonbip-cpu-bctask\",\n"
            + "\"os.name\":\"Linux\",\n"
            + "\"domain.iuap-data-docreport\":\"https://yonbip.diwork.com/iuap-data-docreport\",\n"
            + "\"domain.yonbip-hr-pmpbc\":\"https://yonbip.diwork.com/yonbip-hr-pmpbc\",\n"
            + "\"zookeeper.server\":\"10.3.35.180:2181\",\n"
            + "\"java.vendor.url.bug\":\"http://bugreport.sun.com/bugreport/\",\n"
            + "\"domain.yonbip-hr-train\":\"https://yonbip.diwork.com/yonbip-hr-train\",\n"
            + "\"A69.load_type\":\"JSON\",\n"
            + "\"mdd_schema.hrcloud-staff-mgr\":\"iuap_cloud_basedoc\",\n"
            + "\"domain.iuap-yonbuilder-transdata\":\"https://yonbip.diwork.com/iuap-yonbuilder-transdata\",\n"
            + "\"domain.yonbip-hr-paybiz\":\"https://yonbip.diwork.com/yonbip-hr-paybiz\",\n"
            + "\"domain.yonbip-hr-insure\":\"https://yonbip.diwork.com/yonbip-hr-insure\",\n"
            + "\"os.arch\":\"amd64\",\n"
            + "\"user.name\":\"root\",\n"
            + "\"domain.yonbip-fi-arap\":\"https://yonbip.diwork.com/yonbip-fi-arap\",\n"
            + "\"mdd_schema.znbz\":\"znbz\",\n"
            + "\"domain.yonbip-hr-infoset\":\"https://yonbip.diwork.com/yonbip-hr-infoset\",\n"
            + "\"domain.yonbip-hr-otr\":\"https://yonbip.diwork.com/yonbip-hr-otr\",\n"
            + "\"sun.java.command\":\"/app/yms.jar\",\n"
            + "\"domain.yonbip-hr-doc\":\"https://yonbip.diwork.com/yonbip-hr-doc\",\n"
            + "\"domain.yonbip-mkt-pdc\":\"https://yonbip.diwork.com/yonbip-mkt-pdc\",\n"
            + "\"yonbip-ec-php-ucenter-web-acl\":\"https://yonbip.diwork.com/yonbip-ec-php-ucenter/web_acl\",\n"
            + "\"domain.yonbip-hr-calendar\":\"https://yonbip.diwork.com/yonbip-hr-calendar\",\n"
            + "\"domain.yonbip-hr-tmcal\":\"https://yonbip.diwork.com/yonbip-hr-tmcal\",\n"
            + "\"mdd_schema.IMP-PES\":\"imp_pes\",\n"
            + "\"domain.yonbip-ec-contacts\":\"https://yonbip.diwork.com/yonbip-ec-contacts\",\n"
            + "\"domain.iuap-yonbuilder-mobilenode\":\"https://yonbip.diwork.com/iuap-yonbuilder-mobilenode\",\n"
            + "\"domain.yonbip-hr-attenddoc\":\"https://yonbip.diwork.com/yonbip-hr-attenddoc\",\n"
            + "\"domain.yonbip-mkt-promotion2c\":\"https://yonbip.diwork.com/yonbip-mkt-promotion2c\",\n"
            + "\"domain.yonbip-fi-ml\":\"https://yonbip.diwork.com/yonbip-fi-ml\",\n"
            + "\"user.country\":\"US\",\n"
            + "\"mdd_schema.yonbip-fi-ctmtlm\":\"ctmtlm\",\n"
            + "\"domain.bip-idoc\":\"https://idoc.diwork.com\",\n"
            + "\"yht_app_base_url\":\"https://ecos.yonyoucloud.com/assist/rest\",\n"
            + "\"domain.iuap-data-analytic\":\"https://yonbip.diwork.com/iuap-data-analytic\",\n"
            + "\"docker.baseimage.url\":\"ycr.yonyoucloud.com/base/\",\n"
            + "\"domain.yonbip-hr-tm\":\"https://yonbip.diwork.com/yonbip-hr-tm\",\n"
            + "\"mdd_schema.requirementsplanning\":\"requirements_planning\",\n"
            + "\"domain.yonbip-ec-form-exchange\":\"https://yonbip.diwork.com/yonbip-ec-form-exchange\",\n"
            + "\"domain.yonbip-mkt-member\":\"https://yonbip.diwork.com/yonbip-mkt-member\",\n"
            + "\"domain.yonbip-cpu-mall\":\"https://yonbip.diwork.com/yonbip-cpu-mall\",\n"
            + "\"domain.yonbip-hr-ssc\":\"https://yonbip.diwork.com/yonbip-hr-ssc\",\n"
            + "\"domain.yonbip-ec-php-ucenter\":\"https://yonbip.diwork.com/yonbip-ec-php-ucenter\",\n"
            + "\"mdd_schema.QMS-QIT\":\"qms_qit\",\n"
            + "\"domain.yonbip-fi-expsocrfile\":\"https://yonbip.diwork.com/yonbip-fi-expsocrfile\",\n"
            + "\"domain.iuap-aip-publish\":\"https://yonbip.diwork.com/iuap-aip-publish\",\n"
            + "\"docker.image.url\":\"dockerhub.yonyoucloud.com\",\n"
            + "\"A69.meta_res_path\":\"classpath*:meta-models/*.xml\",\n"
            + "\"domain.yonbip-mm-ilsle\":\"https://yonbip.diwork.com/yonbip-mm-ilsle\",\n"
            + "\"java.endorsed.dirs\":\"/usr/local/java/jre/lib/endorsed\",\n"
            + "\"domain.yonbip-pm-revexp\":\"https://yonbip.diwork.com/yonbip-pm-revexp\",\n"
            + "\"domain.yonbip-fi-note\":\"https://yonbip.diwork.com/yonbip-fi-note\",\n"
            + "\"domain.yonbip-scm-stock\":\"https://yonbip.diwork.com/yonbip-scm-stock\",\n"
            + "\"domain.iuap-market-search\":\"https://yonbip.diwork.com/iuap-market-search\",\n"
            + "\"domain.yonbip-hr-corereport\":\"https://yonbip.diwork.com/yonbip-hr-corereport\",\n"
            + "\"mdd_schema.yonbip-fi-ctmgrm\":\"ctmgrm\",\n"
            + "\"java.vm.specification.version\":\"1.8\",\n"
            + "\"domain.yonbip-fi-sepmdcp\":\"https://yonbip.diwork.com/yonbip-fi-sepmdcp\",\n"
            + "\"domain.yonbip-hr-paycal\":\"https://yonbip.diwork.com/yonbip-hr-paycal\",\n"
            + "\"domain.yonbip-hr-import\":\"https://yonbip.diwork.com/yonbip-hr-import\",\n"
            + "\"domain.yonbip-ec-project\":\"https://yonbip.diwork.com/yonbip-ec-project\",\n"
            + "\"domain.yonbip-ec-camp\":\"https://yonbip.diwork.com/yonbip-ec-camp\",\n"
            + "\"java.awt.headless\":\"true\",\n"
            + "\"domain.yonbip-am-ambd\":\"https://yonbip.diwork.com/yonbip-am-ambd\",\n"
            + "\"domain.yonbip-am-aom\":\"https://yonbip.diwork.com/yonbip-am-aom\",\n"
            + "\"domain.yonbip-mm-aem\":\"https://yonbip.diwork.com/yonbip-mm-aem\",\n"
            + "\"domain.yonbip-mm-mfmrp\":\"https://yonbip.diwork.com/yonbip-mm-mfmrp\",\n"
            + "\"catalina.base\":\"/root/.yms/home/49/temp\",\n"
            + "\"domain.yonbip-hr-org\":\"https://yonbip.diwork.com/yonbip-hr-org\",\n"
            + "\"mdd_schema.ucf-staff-center\":\"iuap_cloud_basedoc\",\n"
            + "\"mdd_schema.productcenter\":\"ugoods\",\n"
            + "\"domain.yonbip-am-aimreport\":\"https://yonbip.diwork.com/yonbip-am-aimreport\",\n"
            + "\"java.vendor\":\"Oracle Corporation\",\n"
            + "\"yonbip-ec-php-ucenter-web-down\":\"https://yonbip.diwork.com/yonbip-ec-php-ucenter/web_down\",\n"
            + "\"file.separator\":\"/\",\n"
            + "\"domain.yonbip-hr-tmbase\":\"https://yonbip.diwork.com/yonbip-hr-tmbase\",\n"
            + "\"domain.yonbip-ec-iform\":\"https://yb.diwork.com/iform_web\",\n"
            + "\"mdd_schema.hrcloud-attend\":\"hrattenddb\",\n"
            + "\"accesscenter_sign_url\":\"https://developer.yonyoucloud.com/accesscenter/api/v1/access/signkey\",\n"
            + "\"mdd_schema.udinghuo\":\"uorders\",\n"
            + "\"domain.iuap-data-nlp\":\"https://yonbip.diwork.com/iuap-data-nlp\",\n"
            + "\"yms.redis.disable.sharedpool\":\"true\",\n"
            + "\"mdd_schema.yycrm\":\"crm_prod\",\n"
            + "\"sun.java.launcher\":\"SUN_STANDARD\",\n"
            + "\"domain.yonbip-mm-adm\":\"https://yonbip.diwork.com/yonbip-mm-adm\",\n"
            + "\"domain.yonbip-hr-contract\":\"https://yonbip.diwork.com/yonbip-hr-contract\",\n"
            + "\"domain.iuap-apcom-messagecenter\":\"https://yonbip.diwork.com/iuap-apcom-messagecenter\",\n"
            + "\"mdd_schema.sact\":\"sact\",\n"
            + "\"yht.expiredTs\":\"1605261431344\",\n"
            + "\"UAP.KDF.PRF\":\"HmacSHA1\",\n"
            + "\"elastic.port\":\"9200\",\n"
            + "\"domain.yonbip-scm-sact\":\"https://yonbip.diwork.com/yonbip-scm-sact\",\n"
            + "\"domain.yonbip-ec-announce\":\"https://yonbip.diwork.com/yonbip-ec-announce\",\n"
            + "\"java.library.path\":\"/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib\",\n"
            + "\"domain.iuap-aip-gateway\":\"https://yonbip.diwork.com/iuap-aip-gateway\",\n"
            + "\"yht.appId\":\"412bf761-2de6-4f4d-b00a-5091538b6113\",\n"
            + "\"domain.iuap-apcom-org\":\"https://yonbip.diwork.com/iuap-apcom-org\",\n"
            + "\"domain.yonbip-cpu-sourcing\":\"https://yonbip.diwork.com/yonbip-cpu-sourcing\",\n"
            + "\"yht.client_id\":\"63\",\n"
            + "\"domain.iuap-yonbuilder-engine\":\"https://developer.yonyoucloud.com/iuap-yonbuilder-engine\",\n"
            + "\"mdd_schema.yssupplier\":\"ugoods\",\n"
            + "\"sun.arch.data.model\":\"64\",\n"
            + "\"java.naming.factory.initial\":\"iuap.yms.naming.YmsJndiContextFactory\",\n"
            + "\"mdd_schema.hrcloud-talent-basedoc\":\"iuap_cloud_basedoc\",\n"
            + "\"domain.yonbip-hr-budget\":\"https://yonbip.diwork.com/yonbip-hr-budget\",\n"
            + "\"domain.yonbip-mkt-sddc\":\"https://yonbip.diwork.com/yonbip-mkt-sddc\",\n"
            + "\"domain.yonbip-fi-coa\":\"https://yonbip.diwork.com/yonbip-fi-coa\",\n"
            + "\"path.separator\":\":\",\n"
            + "\"sun.io.unicode.encoding\":\"UnicodeLittle\",\n"
            + "\"domain.yonbip-fi-it\":\"https://yonbip.diwork.com/yonbip-fi-it\",\n"
            + "\"domain.yonbip-fi-ia-extend\":\"https://yonbip.diwork.com/yonbip-fi-ia-extend\",\n"
            + "\"domain.iuap-data-datafusion\":\"https://yonbip.diwork.com/iuap-data-datafusion\",\n"
            + "\"domain.iuap-aip-package\":\"https://yonbip.diwork.com/iuap-aip-package\",\n"
            + "\"domain.iuap-metadata-designer\":\"https://yonbip.diwork.com/iuap-metadata-designer\",\n"
            + "\"user.language\":\"enu\",\n"
            + "\"domain.yonbip-mkt-crmwebnode\":\"https://yonbip.diwork.com/yonbip-mkt-crmwebnode\",\n"
            + "\"domain.yonbip-cpu-suppliermgr\":\"https://yonbip.diwork.com/yonbip-cpu-suppliermgr\",\n"
            + "\"yht_enterprise_base_url\":\"https://euc.yonyoucloud.com/enterprise/rest\",\n"
            + "\"mdd_schema.IMP-DFM-EMS\":\"imp_ems\",\n"
            + "\"domain.yonbip-ec-php-api-rest-pad\":\"https://yonbip.diwork.com/yonbip-ec-php-api-rest/pad-api\",\n"
            + "\"domain.yonbip-fi-fcweb\":\"https://yonbip.diwork.com/yonbip-fi-fcweb\",\n"
            + "\"domain.yonbip-mkt-udhtpi\":\"https://yonbip.diwork.com/yonbip-mkt-udhtpi\",\n"
            + "\"domain.yonbip-mid-sscia\":\"https://yonbip.diwork.com/yonbip-mid-sscia\",\n"
            + "\"domain.yonbip-hr-pm\":\"https://yonbip.diwork.com/yonbip-hr-pm\",\n"
            + "\"domain.yonbip-mm-aiot\":\"https://yonbip.diwork.com/yonbip-mm-aiot\",\n"
            + "\"domain.yonbip-fi-ia\":\"https://yonbip.diwork.com/yonbip-fi-ia\",\n"
            + "\"uap.system.properties.mode\":\"2\",\n"
            + "\"domain.yonbip-fi-cloud\":\"https://yonbip.diwork.com/yonbip-fi-cloud\",\n"
            + "\"domain.yonbip-fi-ia-in\":\"https://yonbip.diwork.com/yonbip-fi-ia-in\",\n"
            + "\"mdd_schema.productionorder\":\"production_order\",\n"
            + "\"domain.yonbip-hr-paybizo\":\"https://yonbip.diwork.com/yonbip-hr-paybizo\",\n"
            + "\"java.class.version\":\"52.0\",\n"
            + "\"domain.iuap-aip-searchcrawl\":\"https://yonbip.diwork.com/iuap-aip-searchcrawl\",\n"
            + "\"domain.yonbip-mkt-sdwebnode\":\"https://yonbip.diwork.com/yonbip-mkt-sdwebnode\",\n"
            + "\"domain.yonbip-hr-competency\":\"https://yonbip.diwork.com/yonbip-hr-competency\",\n"
            + "\"domain.yonbip-hr-os\":\"https://yonbip.diwork.com/yonbip-hr-os\",\n"
            + "\"domain.yonbip-ec-php-api\":\"https://yonbip.diwork.com/yonbip-ec-php-api\",\n"
            + "\"domain.iuap-yonbuilder-mobile\":\"https://yonbip.diwork.com/iuap-yonbuilder-mobile\",\n"
            + "\"mdd_schema.aum\":\"amc_aum\",\n"
            + "\"domain.yonbip-scm-scmsa\":\"https://yonbip.diwork.com/yonbip-scm-scmsa\",\n"
            + "\"mdd_schema.umall\":\"upmalls\",\n"
            + "\"sun.nio.ch.bugLevel\":\"\",\n"
            + "\"domain.yonbip-mkt-retailwebnode\":\"https://yonbip.diwork.com/yonbip-mkt-retailwebnode\",\n"
            + "\"mdd_schema.PLM-PLM-PSDM\":\"imp_plm\",\n"
            + "\"httpclient.MaxTotal\":\"100\",\n"
            + "\"file.encoding.pkg\":\"sun.io\",\n"
            + "\"sun.cpu.endian\":\"little\",\n"
            + "\"domain.yonbip-scm-scmf\":\"https://yonbip.diwork.com/yonbip-scm-scmf\",\n"
            + "\"domain.yonbip-mkt-mallapp\":\"https://yonbip.diwork.com/yonbip-mkt-mallapp\",\n"
            + "\"mdd_schema.yonbip-fi-ctmlgm\":\"ctmlgm\",\n"
            + "\"domain.yonbip-pm-workhours\":\"https://yonbip.diwork.com/yonbip-pm-workhours\",\n"
            + "\"domain.yonbip-fi-expsapct\":\"https://yonbip.diwork.com/yonbip-fi-expsapct\",\n"
            + "\"mdd_schema.rmm\":\"amc_mro\",\n"
            + "\"domain.iuap-yonbuilder-designer\":\"https://yonbip.diwork.com/iuap-yonbuilder-designer\",\n"
            + "\"domain.yonbip-hr-tmsign\":\"https://yonbip.diwork.com/yonbip-hr-tmsign\",\n"
            + "\"domain.yonbip-mkt-vip\":\"https://yonbip.diwork.com/yonbip-mkt-vip\",\n"
            + "\"domain.yonbip-ec-php-api-rest-web\":\"https://web-api.diwork.com\",\n"
            + "\"domain.yonbip-fi-eafmid\":\"https://yonbip.diwork.com/yonbip-fi-eafmid\",\n"
            + "\"yht.sysid\":\"diwork\",\n"
            + "\"java.home\":\"/usr/local/java/jre\",\n"
            + "\"domain.yonbip-scm-inttrade\":\"https://yonbip.diwork.com/yonbip-scm-inttrade\",\n"
            + "\"domain.yonbip-ec-idocview\":\"https://preview.diwork.com\",\n"
            + "\"domain.yonbip-mm-dfm\":\"https://yonbip.diwork.com/yonbip-mm-dfm\",\n"
            + "\"domain.yonbip-mm-mfed\":\"https://yonbip.diwork.com/yonbip-mm-mfed\",\n"
            + "\"domain.yonbip-fi-arap-in\":\"https://yonbip.diwork.com/yonbip-fi-arap-in\",\n"
            + "\"mdd_schema.transtype\":\"iuap_cloud_basedoc\",\n"
            + "\"domain.yonbip-ec-openapi\":\"https://openapi.diwork.com\",\n"
            + "\"yht_cas_url\":\"https://euc.yonyoucloud.com/cas\",\n"
            + "\"A69.metadataCacheMaxSize\":\"2000\",\n"
            + "\"domain.yonbip-ec-php-mobile\":\"https://yonbip.diwork.com/yonbip-ec-php-mobile\",\n"
            + "\"mdd_schema.engineeringdata\":\"engineering_data\",\n"
            + "\"domain.iuap-uuas-user\":\"https://yonbip.diwork.com/iuap-uuas-user\",\n"
            + "\"mdd_schema.ambd\":\"amc_ambd\",\n"
            + "\"elastic.cluster.hosts\":\"172.20.45.257:9002\",\n"
            + "\"mdd_schema.MDDHR\":\"hrcloud\",\n"
            + "\"domain.yonbip-mkt-usmp\":\"https://yonbip.diwork.com/yonbip-mkt-usmp\",\n"
            + "\"domain.iuap-ipaas-dataintegration\":\"https://yonbip.diwork.com/iuap-ipaas-dataintegration\",\n"
            + "\"secondary.access.key\":\"secondary.access.key\",\n"
            + "\"domain.yonbip-am-rmmreport\":\"https://yonbip.diwork.com/yonbip-am-rmmreport\",\n"
            + "\"domain.yonbip-cpu-lawbid\":\"https://yonbip.diwork.com/yonbip-cpu-lawbid\",\n"
            + "\"domain.iuap-data-common\":\"https://yonbip.diwork.com/iuap-data-common\",\n"
            + "\"domain.iuap-aip-search\":\"https://yonbip.diwork.com/iuap-aip-search\",\n"
            + "\"domain.yonbip-hr-staffmgr\":\"https://yonbip.diwork.com/yonbip-hr-staffmgr\",\n"
            + "\"snowflake.zkserver\":\"10.3.35.180:2182\",\n"
            + "\"domain.yonbip-mid-sscibot\":\"https://yonbip.diwork.com/yonbip-mid-sscibot\",\n"
            + "\"A69.pipelinecode\":\"metadatachannel_online\",\n"
            + "\"domain.yonbip-hr-staffmgo\":\"https://yonbip.diwork.com/yonbip-hr-staffmgo\",\n"
            + "\"ignorePattern\":\".*\\\\.js,.*\\\\.css,.*\\\\.jsx,/rest/.*,/style/.*,/index\\\\.html,/controller/register/.*,/CloudRemoteCall/*\",\n"
            + "\"domain.yonbip-fi-fa\":\"https://yonbip.diwork.com/yonbip-fi-fa\",\n"
            + "\"domain.yonbip-mm-wjm\":\"https://yonbip.diwork.com/yonbip-mm-wjm\",\n"
            + "\"domain.yonbip-cpu-bcprice\":\"https://yonbip.diwork.com/yonbip-cpu-bcprice\",\n"
            + "\"domain.yonbip-mkt-yxybaseweb\":\"https://yonbip.diwork.com/yonbip-mkt-yxybaseweb\",\n"
            + "\"mdd_schema.IMP-GDS\":\"imp_plm\",\n"
            + "\"domain.yonbip-cpu-yop\":\"https://yonbip.diwork.com/yonbip-cpu-yop\",\n"
            + "\"mdd_schema.drft\":\"ctmdrft\",\n"
            + "\"domain.iuap-apcom-i18n\":\"https://yonbip.diwork.com/iuap-apcom-i18n\",\n"
            + "\"domain.yonbip-am-aim\":\"https://yonbip.diwork.com/yonbip-am-aim\",\n"
            + "\"domain.iuap-egacy-uitemplate\":\"https://yonbip.diwork.com/iuap-egacy-uitemplate\",\n"
            + "\"mdd_schema.IMP-SCS\":\"imp_plm\",\n"
            + "\"java.protocol.handler.pkgs\":\"org.springframework.boot.loader|org.springframework.boot.loader\",\n"
            + "\"domain.yonbip-hr-attendprocess\":\"https://yonbip.diwork.com/yonbip-hr-attendprocess\",\n"
            + "\"mdd_schema.IMP-BASE\":\"imp_plm\",\n"
            + "\"domain.yonbip-fi-pcm\":\"https://yonbip.diwork.com/yonbip-fi-pcm\",\n"
            + "\"domain.yonbip-hr-prealert\":\"https://yonbip.diwork.com/yonbip-hr-prealert\",\n"
            + "\"domain.iuap-apcom-event\":\"https://yonbip.diwork.com/iuap-apcom-event\",\n"
            + "\"sun.management.compiler\":\"HotSpot 64-Bit Tiered Compilers\",\n"
            + "\"domain.iuap-uuas-cas\":\"https://euc.yonyoucloud.com/cas\",\n"
            + "\"mdd_schema.upu\":\"upurchase\",\n"
            + "\"domain.iuap-00-market\":\"https://yonbip.diwork.com/iuap-00-market\",\n"
            + "\"domain.yonbip-hr-payconfig\":\"https://yonbip.diwork.com/yonbip-hr-payconfig\",\n"
            + "\"license-server-url\":\"http://127.0.0.1/iuap-licenseserver/client\",\n"
            + "\"domain.yonbip-fi-cloud-in\":\"https://yonbip.diwork.com/yonbip-fi-cloud-in\",\n"
            + "\"domain.yonbip-mm-plmec\":\"https://yonbip.diwork.com/yonbip-mm-plmec\",\n"
            + "\"domain.yonbip-ec-meeting\":\"https://yonbip.diwork.com/yonbip-ec-meeting\",\n"
            + "\"domain.yonbip-fi-ds\":\"https://yonbip.diwork.com/yonbip-fi-ds\",\n"
            + "\"domain.iuap-yonbuilder-j2v8debug\":\"https://yonbip.diwork.com/iuap-yonbuilder-j2v8debug\",\n"
            + "\"domain.iuap-yonbuilder-businessflow\":\"https://yonbip.diwork.com/iuap-yonbuilder-businessflow\",\n"
            + "\"yht_client_credential_path\":\"authfile.properties\",\n"
            + "\"mdd_schema.ucf-amc-aum\":\"amc_aum\",\n"
            + "\"domain.yonbip-mm-tbs\":\"https://yonbip.diwork.com/yonbip-mm-tbs\",\n"
            + "\"domain.yonbip-mm-plan\":\"https://yonbip.diwork.com/yonbip-mm-plan\",\n"
            + "\"java.vm.specification.vendor\":\"Oracle Corporation\",\n"
            + "\"domain.yonbip-cpu-bid\":\"https://yonbip.diwork.com/yonbip-cpu-bid\",\n"
            + "\"java.vm.name\":\"Java HotSpot(TM) 64-Bit Server VM\",\n"
            + "\"domain.yonbip-mkt-dst\":\"https://yonbip.diwork.com/yonbip-mkt-dst\",\n"
            + "\"java.naming.factory.url.pkgs\":\"iuap.yms.naming\",\n"
            + "\"domain.iuap-api-auth\":\"https://yonbip.diwork.com/iuap-api-auth\",\n"
            + "\"domain.yonbip-mkt-udhsdwebnode\":\"https://yonbip.diwork.com/yonbip-mkt-udhsdwebnode\",\n"
            + "\"mdd_schema.ucfbasedoc\":\"iuap_cloud_basedoc\",\n"
            + "\"domain.yonbip-ec-schedule\":\"https://yonbip.diwork.com/yonbip-ec-schedule\",\n"
            + "\"mdd_schema.ucf-amc-rmm\":\"amc_mro\",\n"
            + "\"domain.iuap-legacy-ref\":\"https://yonbip.diwork.com/iuap-legacy-ref\",\n"
            + "\"java.io.tmpdir\":\"/tmp\",\n"
            + "\"java.vendor.url\":\"http://java.oracle.com/\",\n"
            + "\"domain.yonbip-fi-fa-in\":\"https://yonbip.diwork.com/yonbip-fi-fa-in\",\n"
            + "\"domain.yonbip-hr-corecontract\":\"https://yonbip.diwork.com/yonbip-hr-corecontract\",\n"
            + "\"domain.yonbip-fi-ctmdrft\":\"https://yonbip.diwork.com/yonbip-fi-ctmdrft\",\n"
            + "\"domain.yonbip-fi-ctmstct\":\"https://yonbip.diwork.com/yonbip-fi-ctmstct\",\n"
            + "\"zklock.url\":\"10.3.35.180:2182\",\n"
            + "\"yht.key\":\"745443526541646157686e536c6567786b524d56\",\n"
            + "\"domain.iuap-apcom-staff\":\"https://yonbip.diwork.com/iuap-apcom-staff\",\n"
            + "\"domain.iuap-data-qa\":\"https://yonbip.diwork.com/iuap-data-qa\",\n"
            + "\"mdd_schema.sharedservicecenter\":\"shared_service\",\n"
            + "\"domain.yonbip-ec-cooperation\":\"https://yonbip.diwork.com/yonbip-ec-cooperation\",\n"
            + "\"domain.iuap-metadata-import\":\"https://yonbip.diwork.com/iuap-metadata-import/exceltrain\",\n"
            + "\"sun.boot.library.path\":\"/usr/local/java/jre/lib/amd64\",\n"
            + "\"domain.yonbip-fi-sepmpro\":\"https://yonbip.diwork.com/yonbip-fi-sepmpro\",\n"
            + "\"domain.yonbip-fi-etl\":\"https://yonbip.diwork.com/yonbip-fi-etl\",\n"
            + "\"domain.iuap-apcom-auth\":\"https://yonbip.diwork.com/iuap-apcom-auth\",\n"
            + "\"domain.yonbip-fi-cc\":\"https://yonbip.diwork.com/yonbip-fi-cc\",\n"
            + "\"mdd_schema.yonyoufi\":\"fiproduct\",\n"
            + "\"domain.iuap-open-event\":\"https://yonbip.diwork.com/iuap-open-event\",\n"
            + "\"docker.registry.username\":\"registry\",\n"
            + "\"domain.yonbip-hr-bpm\":\"https://yonbip.diwork.com/yonbip-hr-bpm\",\n"
            + "\"domain.yonbip-fi-ctmbam\":\"https://yonbip.diwork.com/yonbip-fi-ctmbam\",\n"
            + "\"domain.yonbip-ec-link\":\"https://yonbip.diwork.com/yonbip-ec-link\",\n"
            + "\"domain.yonbip-fi-ctmtlm\":\"https://yonbip.diwork.com/yonbip-fi-ctmtlm\",\n"
            + "\"domain.yonbip-scm-scmmp\":\"https://yonbip.diwork.com/yonbip-scm-scmmp\",\n"
            + "\"mdd_schema.IMP-PLM-PSDM\":\"imp_plm\",\n"
            + "\"java.runtime.name\":\"Java(TM) SE Runtime Environment\",\n"
            + "\"yht_apps_tenant_base_url\":\"https://apcenter.yonyoucloud.com/apptenant/rest\",\n"
            + "\"domain.iuap-apdoc-basedoc\":\"https://yonbip.diwork.com/iuap-apdoc-basedoc\",\n"
            + "\"primary.access.secret\":\"primary.access.secret\",\n"
            + "\"domain.yonbip-ec-php-api-rest-dwweb\":\"https://dwweb-api.diwork.com\",\n"
            + "\"domain.yonbip-fi-eaffile\":\"https://yonbip.diwork.com/yonbip-fi-eaffile\",\n"
            + "\"mdd_schema.QMS-DFM\":\"qms_dfm\",\n"
            + "\"mdd_schema.IMP-EMS\":\"imp_ems\",\n"
            + "\"domain.yonbip-ec-php-api-rest-pc\":\"https://yonbip.diwork.com/yonbip-ec-php-api-rest/pc-api\",\n"
            + "\"mdd_schema.aom\":\"amc_aom\",\n"
            + "\"sun.cpu.isalist\":\"\",\n"
            + "\"domain.iuap-yonbuilder-sandbox\":\"https://yonbip.diwork.com/iuap-yonbuilder-sandbox\",\n"
            + "\"domain.yonbip-mkt-retailweb\":\"https://yonbip.diwork.com/yonbip-mkt-retailweb\",\n"
            + "\"mdd_schema.IMP-HSE\":\"imp_hse\",\n"
            + "\"domain.yonbip-ec-support\":\"https://yonbip.diwork.com/yonbip-ec-support\",\n"
            + "\"domain.iuap-00-im\":\"https://im.yonyoucloud.com\",\n"
            + "\"domain.yonbip-mkt-mudhwebnode\":\"https://yonbip.diwork.com/yonbip-mkt-mudhwebnode\",\n"
            + "\"user.home\":\"/root\",\n"
            + "\"domain.yonbip-hr-pmtmp\":\"https://yonbip.diwork.com/yonbip-hr-pmtmp\",\n"
            + "\"domain.yonbip-fi-ctmgrm\":\"https://yonbip.diwork.com/yonbip-fi-ctmgrm\",\n"
            + "\"domain.yonbip-hr-staff\":\"https://yonbip.diwork.com/yonbip-hr-staff\",\n"
            + "\"mdd_schema.usmp\":\"usmp\",\n"
            + "\"domain.yonbip-hr-pay\":\"https://yonbip.diwork.com/yonbip-hr-pay\",\n"
            + "\"domain.yonbip-am-ambdimport\":\"https://yonbip.diwork.com/yonbip-am-ambdimport\",\n"
            + "\"java.specification.name\":\"Java Platform API Specification\",\n"
            + "\"domain.yonbip-ec-php-esn-diwork\":\"https://yonbip.diwork.com/yonbip-ec-php-esn-diwork\",\n"
            + "\"domain.iuap-blockchain-mgt\":\"https://yonbip.diwork.com/iuap-blockchain-mgt\",\n"
            + "\"yht.scope\":\"7\",\n"
            + "\"A69.metadataCacheTimeout\":\"36000\",\n"
            + "\"java.specification.vendor\":\"Oracle Corporation\",\n"
            + "\"yht.client_secret\":\"ed0175f5-4b38-497c-a697-4d5cf028188d\",\n"
            + "\"java.version\":\"1.8.0_202\",\n"
            + "\"domain.yonbip-ec-supervision\":\"https://yonbip.diwork.com/yonbip-ec-supervision\",\n"
            + "\"mdd_schema.HR\":\"hrcloud\",\n"
            + "\"domain.yonbip-pm-project\":\"https://yonbip.diwork.com/yonbip-pm-project\",\n"
            + "\"domain.yonbip-hr-osmgr\":\"https://yonbip.diwork.com/yonbip-hr-osmgr\",\n"
            + "\"disconf.filterbyclassloader\":\"true\",\n"
            + "\"domain.yonbip-cpu-baseservice\":\"https://yonbip.diwork.com/yonbip-cpu-baseservice\",\n"
            + "\"mdd_schema.ctm-bam\":\"ctmbam\",\n"
            + "\"mdd_schema.PLM-PLM-PBS\":\"imp_plm\",\n"
            + "\"license-server.url\":\"http://127.0.0.1/iuap-licenseserver/client\",\n"
            + "\"domain.yonbip-am-aumreport\":\"https://yonbip.diwork.com/yonbip-am-aumreport\",\n"
            + "\"mdd_schema.dst\":\"omsdata\",\n"
            + "\"mdd_schema.stwb\":\"ctmstwb\",\n"
            + "\"elastic.username\":\"elastic\",\n"
            + "\"yht_user_server_url\":\"https://euc.yonyoucloud.com\",\n"
            + "\"domain.iuap-00-defdoc\":\"https://yonbip.diwork.com/iuap-00-defdoc\",\n"
            + "\"domain.iuap-api-gateway\":\"https://yonbip.diwork.com/iuap-api-gateway\",\n"
            + "\"UAP.DigitalSignatureKeyLength\":\"1024\",\n"
            + "\"lock.zkserver\":\"10.3.35.180:2182\",\n"
            + "\"PID\":\"49\",\n"
            + "\"domain.iuap-apcom-workflow\":\"https://yonbip.diwork.com/iuap-apcom-workflow\",\n"
            + "\"mdd_schema.uorder\":\"uorders\",\n"
            + "\"domain.yonbip-ec-php-api-rest-mp\":\"https://yonbip.diwork.com/yonbip-ec-php-api-rest/mp-api\",\n"
            + "\"dubbo.registry.zkserver\":\"10.3.35.180:2181\",\n"
            + "\"domain.yonbip-hr-attendsdts\":\"https://yonbip.diwork.com/yonbip-hr-attendsdts\",\n"
            + "\"domain.iuap-metadata-ui\":\"https://yonbip.diwork.com/iuap-metadata-ui\",\n"
            + "\"OSP.SDK.VERSION\":\"0.0.6\",\n"
            + "\"domain.iuap-apdoc-vendor\":\"https://yonbip.diwork.com/iuap-apdoc-vendor\",\n"
            + "\"domain.iuap-metadata-extend\":\"https://yonbip.diwork.com/iuap-metadata-extend\",\n"
            + "\"domain.yonbip-ec-file\":\"https://yonbip.diwork.com/yonbip-ec-file\",\n"
            + "\"line.separator\":\"\\n\",\n"
            + "\"java.specification.version\":\"1.8\",\n"
            + "\"java.vm.info\":\"mixed mode\",\n"
            + "\"domain.yonbip-ec-wps\":\"https://ecwps.diwork.com\",\n"
            + "\"domain.iuap-apcom-file\":\"https://yonbip.diwork.com/iuap-apcom-file\",\n"
            + "\"mdd_schema.membercenter\":\"yilian\",\n"
            + "\"domain.esn-base-file\":\"https://yonbip.diwork.com/iuap-apcom-file\",\n"
            + "\"domain.yonbip-ec-business-expansion\":\"https://yonbip.diwork.com/yonbip-ec-business-expansion\",\n"
            + "\"domain.yonbip-mkt-mkc2b\":\"https://yonbip.diwork.com/yonbip-mkt-mkc2b\",\n"
            + "\"sun.boot.class.path\":\"/usr/local/java/jre/lib/resources.jar:/usr/local/java/jre/lib/rt.jar:/usr/local/java/jre/lib/sunrsasign.jar:/usr/local/java/jre/lib/jsse.jar:/usr/local/java/jre/lib/jce.jar:/usr/local/java/jre/lib/charsets.jar:/usr/local/java/jre/lib/jfr.jar:/usr/local/java/jre/classes\",\n"
            + "\"mdd_schema.retail\":\"uretaildata\",\n"
            + "\"domain.yonbip-fi-ctmcspl\":\"https://yonbip.diwork.com/yonbip-fi-ctmcspl\",\n"
            + "\"domain.yonbip-pm-projectme\":\"https://yonbip.diwork.com/yonbip-pm-projectme\",\n"
            + "\"domain.yonbip-mm-eps\":\"https://yonbip.diwork.com/yonbip-mm-eps\",\n"
            + "\"domain.iuap-uuas-tenant\":\"https://yonbip.diwork.com/iuap-uuas-tenant\",\n"
            + "\"mdd_schema.fdtr\":\"ctmfdtr\",\n"
            + "\"domain.yonbip-mkt-mall\":\"https://yonbip.diwork.com/yonbip-mkt-mall\",\n"
            + "\"mdd_schema.ucf-amc-aom\":\"amc_aom\",\n"
            + "\"domain.yonbip-fi-pub\":\"https://yonbip.diwork.com/yonbip-fi-pub\",\n"
            + "\"domain.yonbip-fi-eafdocfile\":\"https://yonbip.diwork.com/yonbip-fi-eafdocfile\",\n"
            + "\"secondary.access.secret\":\"secondary.access.secret\",\n"
            + "\"httpclient.MaxPerRoute\":\"100\",\n"
            + "\"domain.yonbip-fi-ctmstwb\":\"https://yonbip.diwork.com/yonbip-fi-ctmstwb\",\n"
            + "\"domain.yonbip-cpu-dop\":\"https://yonbip.diwork.com/yonbip-cpu-dop\",\n"
            + "\"mdd_schema.ctm-stct\":\"ctmstct\",\n"
            + "\"domain.iuap-apcom-workbench\":\"https://yonbip.diwork.com\",\n"
            + "\"domain.yonbip-mkt-mkc2bimport\":\"https://yonbip.diwork.com/yonbip-mkt-mkc2bimport\",\n"
            + "\"domain.yonbip-hr-report\":\"https://yonbip.diwork.com/yonbip-hr-report\",\n"
            + "\"A69.db_dialect\":\"mysql\",\n"
            + "\"domain.iuap-apcom-auditlog\":\"https://yonbip.diwork.com/iuap-apcom-auditlog\",\n"
            + "\"rest.algorithm\":\"HmacSHA1\",\n"
            + "\"domain.iuap-apcom-contract\":\"https://yonbip.diwork.com/iuap-apcom-contract\",\n"
            + "\"domain.yonbip-scm-scmpub\":\"https://yonbip.diwork.com/yonbip-scm-scmpub\",\n"
            + "\"domain.iuap-api-stream\":\"https://yonbip.diwork.com/iuap-api-stream\",\n"
            + "\"java.awt.printerjob\":\"sun.print.PSPrinterJob\",\n"
            + "\"domain.yonbip-fi-maalgo\":\"https://yonbip.diwork.com/yonbip-fi-maalgo\",\n"
            + "\"domain.yonbip-am-aomreport\":\"https://yonbip.diwork.com/yonbip-am-aomreport\",\n"
            + "\"mdd_schema.fima\":\"fima\",\n"
            + "\"domain.yonbip-ec-official\":\"https://yonbip.diwork.com/yonbip-ec-official\",\n"
            + "\"sun.jnu.encoding\":\"UTF-8\",\n"
            + "\"yht.username\":\"diwork_new\",\n"
            + "\"client.credential.path\":\"authfile.properties\",\n"
            + "\"domain.iuap-apdoc-ambd\":\"https://yonbip.diwork.com/iuap-apdoc-ambd\",\n"
            + "\"domain.yonbip-ec-minor\":\"https://yonbip.diwork.com/yonbip-ec-minor\",\n"
            + "\"java.runtime.version\":\"1.8.0_202-b08\",\n"
            + "\"domain.yonbip-fi-ctmlgm\":\"https://yonbip.diwork.com/yonbip-fi-ctmlgm\",\n"
            + "\"sysid\":\"developer\",\n"
            + "\"mdd_schema.uhy\":\"yilian\",\n"
            + "\"domain.yonbip-scm-quote\":\"https://yonbip.diwork.com/yonbip-scm-quote\",\n"
            + "\"UAP.DigitalSignatureAlgorithm\":\"SHA1withRSA\",\n"
            + "\"domain.znbzbx-front\":\"https://yonbip.diwork.com/znbzbx-front\",\n"
            + "\"domain.yonbip-cpu-msgpusher\":\"https://yonbip.diwork.com/yonbip-cpu-msgpusher\",\n"
            + "\"domain.yonbip-hr-setup\":\"https://yonbip.diwork.com/yonbip-hr-setup\",\n"
            + "\"domain.yonbip-ec-base\":\"https://yonbip.diwork.com/yonbip-ec-base\",\n"
            + "\"user.timezone\":\"Asia/Shanghai\",\n"
            + "\"domain.yonbip-hr-talent\":\"https://yonbip.diwork.com/yonbip-hr-talent\",\n"
            + "\"mdd_schema.scmmp\":\"scmmp\",\n"
            + "\"domain.url\":\"https://yonbip.diwork.com\",\n"
            + "\"domain.iuap-apdoc-gateway\":\"https://yonbip.diwork.com/iuap-apdoc-gateway\",\n"
            + "\"domain.yonbip-hr-adapter\":\"https://yonbip.diwork.com/yonbip-hr-adapter\",\n"
            + "\"domain.iuap-metadata-report\":\"https://yonbip.diwork.com/iuap-metadata-report\",\n"
            + "\"domain.yonbip-mkt-crm\":\"https://yonbip.diwork.com/yonbip-mkt-crm\",\n"
            + "\"domain.yonbip-mm-qms\":\"https://yonbip.diwork.com/yonbip-mm-qms\",\n"
            + "\"domain.yonbip-fi-ctmcmp\":\"https://yonbip.diwork.com/yonbip-fi-ctmcmp\",\n"
            + "\"domain.yonbip-fi-eafrecord\":\"https://yonbip.diwork.com/yonbip-fi-eafrecord\",\n"
            + "\"domain.iuap-apcom-coderule\":\"https://yonbip.diwork.com/iuap-apcom-coderule\",\n"
            + "\"mdd_schema.aim\":\"amc_aim\",\n"
            + "\"domain.yonbip-fi-ctmfdtr\":\"https://yonbip.diwork.com/yonbip-fi-ctmfdtr\",\n"
            + "\"java.ext.dirs\":\"/usr/local/java/jre/lib/ext:/usr/java/packages/lib/ext\",\n"
            + "\"domain.iuap-apdoc-finbd\":\"https://yonbip.diwork.com/iuap-apdoc-finbd\",\n"
            + "\"domain.iuap-aip-console\":\"https://yonbip.diwork.com/iuap-aip-console\",\n"
            + "\"domain.yonbip-mm-mfecn\":\"https://yonbip.diwork.com/yonbip-mm-mfecn\",\n"
            + "\"domain.yonbip-mkt-udm\":\"https://yonbip.diwork.com/yonbip-mkt-udm\",\n"
            + "\"domain.yonbip-hr-pub\":\"https://yonbip.diwork.com/yonbip-hr-pub\",\n"
            + "\"domain.yonbip-cpu-search\":\"https://yonbip.diwork.com/yonbip-cpu-search\",\n"
            + "\"domain.yonbip-mkt-udh\":\"https://yonbip.diwork.com/yonbip-mkt-udh\",\n"
            + "\"java.class.path\":\"/app/yms.jar\",\n"
            + "\"mdd_schema.hrcloud-talent\":\"hrcloud\",\n"
            + "\"domain.yonbip-mkt-upmallwebnode\":\"https://yonbip.diwork.com/yonbip-mkt-upmallwebnode\",\n"
            + "\"domain.yonbip-cpu-portal\":\"https://yonbip.diwork.com/yonbip-cpu-portal\",\n"
            + "\"domain.iuap-apcom-scheduler\":\"https://yonbip.diwork.com/iuap-apcom-scheduler\",\n"
            + "\"yht_user_base_url\":\"https://euc.yonyoucloud.com/rest\",\n"
            + "\"domain.yonbip-hr-paycc\":\"https://yonbip.diwork.com/yonbip-hr-paycc\",\n"
            + "\"domain.yonbip-hr-attendreport\":\"https://yonbip.diwork.com/yonbip-hr-attendreport\",\n"
            + "\"mdd_schema.MDDHRPUB\":\"hrcloud\",\n"
            + "\"domain.yonbip-mm-ems\":\"https://yonbip.diwork.com/yonbip-mm-ems\",\n"
            + "\"catalina.home\":\"/root/.yms/home/49/temp\",\n"
            + "\"domain.yonbip-ec-php-esn-web\":\"https://yonbip.diwork.com/yonbip-ec-php-esn-web\",\n"
            + "\"os.version\":\"5.4.109-1.el7.elrepo.x86_64\",\n"
            + "\"docker.registry.password\":\"###\",\n"
            + "\"domain.yonbip-cpu-bcsourcing\":\"https://yonbip.diwork.com/yonbip-cpu-bcsourcing\",\n"
            + "\"mdd_schema.finbd\":\"finbd\",\n"
            + "\"domain.iuap-aip-rpawst\":\"https://yonbip.diwork.com/iuap-aip-rpawst\",\n"
            + "\"domain.yonbip-mm-prm\":\"https://yonbip.diwork.com/yonbip-mm-prm\",\n"
            + "\"domain.yonbip-fi-taxgateway\":\"https://yonbip.diwork.com/tax\",\n"
            + "\"kafka.cluster.hosts\":\"10.3.4.177:9092,10.3.4.154:9092,10.3.4.155:9092\",\n"
            + "\"domain.yonbip-fi-npub\":\"https://yonbip.diwork.com/yonbip-fi-npub\",\n"
            + "\"java.awt.graphicsenv\":\"sun.awt.X11GraphicsEnvironment\",\n"
            + "\"iuap-apcom-bipuser\":\"https://yonbip.diwork.com/iuap-apcom-bipuser\",\n"
            + "\"domain.gpaas.url\":\"https://developer.yonyoucloud.com\",\n"
            + "\"UAP.AUTH.ALG\":\"HMAC\",\n"
            + "\"domain.yonbip-mkt-udhwebnode\":\"https://yonbip.diwork.com/yonbip-mkt-udhwebnode\",\n"
            + "\"java.vm.vendor\":\"Oracle Corporation\",\n"
            + "\"domain.yonbip-hr-staffquery\":\"https://yonbip.diwork.com/yonbip-hr-staffquery\",\n"
            + "\"domain.iuap-aip-vpa\":\"https://yonbip.diwork.com/iuap-aip-vpa\",\n"
            + "\"domain.yonbip-mid-sscsc\":\"https://yonbip.diwork.com/yonbip-mid-sscsc\",\n"
            + "\"mdd_schema.ctm-cmp\":\"ctmcmp\",\n"
            + "\"spring.beaninfo.ignore\":\"true\",\n"
            + "\"domain.yonbip-mkt-vipbiz\":\"https://yonbip.diwork.com/yonbip-mkt-vipbiz\",\n"
            + "\"domain.yonbip-fi-expsbtrs\":\"https://yonbip.diwork.com/yonbip-fi-expsbtrs\",\n"
            + "\"isPremises\":\"false\",\n"
            + "\"mdd_schema.ucf-amc-ambd\":\"amc_ambd\",\n"
            + "\"domain.iuap-00-areaformat\":\"https://yonbip.diwork.com/iuap-00-areaformat\",\n"
            + "\"domain.iuap-aip-rpa\":\"https://yonbip.diwork.com/iuap-aip-rpa\",\n"
            + "\"domain.yonbip-ec-php-api-rest-inapi\":\"https://in-api.diwork.com\",\n"
            + "\"domain.yonbip-scm-pu\":\"https://yonbip.diwork.com/yonbip-scm-pu\",\n"
            + "\"domain.iuap-metadata-base\":\"https://yonbip.diwork.com/iuap-metadata-base\",\n"
            + "\"domain.iuap-apcom-bipuser\":\"https://yonbip.diwork.com/iuap-apcom-bipuser\",\n"
            + "\"domain.yonbip-cpu-bcres\":\"https://yonbip.diwork.com/yonbip-cpu-bcres\",\n"
            + "\"domain.iuap-apcom-staffdoc\":\"https://yonbip.diwork.com/iuap-apcom-staffdoc\",\n"
            + "\"mdd_schema.IMP-PLM-WIDGET\":\"imp_plm\",\n"
            + "\"domain.iuap-legacy-translate\":\"https://yonbip.diwork.com/iuap-legacy-translate\",\n"
            + "\"elastic.host\":\"172.20.45.257\",\n"
            + "\"catalina.useNaming\":\"false\",\n"
            + "\"mdd_schema.mall\":\"upmalls\",\n"
            + "\"file.encoding\":\"UTF-8\",\n"
            + "\"domain.iuap-apdoc-material\":\"https://yonbip.diwork.com/iuap-apdoc-material\",\n"
            + "\"domain.yonbip-mm-mfpo\":\"https://yonbip.diwork.com/yonbip-mm-mfpo\",\n"
            + "\"yht.servername\":\"https://yonbip.diwork.com\",\n"
            + "\"mdd_schema.marketingbill\":\"uorders\",\n"
            + "\"mdd_schema.ucf-org-center\":\"iuap_cloud_basedoc\",\n"
            + "\"domain.yonbip-hr-pmokr\":\"https://yonbip.diwork.com/yonbip-hr-pmokr\",\n"
            + "\"awt.toolkit\":\"sun.awt.X11.XToolkit\",\n"
            + "\"mdd_schema.ctm-cspl\":\"ctmcspl\",\n"
            + "\"domain.yonbip-ec-logger\":\"https://yonbip.diwork.com/yonbip-ec-logger\",\n"
            + "}\n";

    m2 = (HashMap<String, String>) JSONObject.parseObject(s2, Map.class);
    LogUtils.foal(m2,"");

    Map<String, String> m3;


    String domainSchemaPreKey = "mdd_schema.";
    m3 = m2.entrySet().stream()
            .filter(e -> e.getKey().startsWith(domainSchemaPreKey))
            .collect(
                    Collectors.toMap(p -> p.getKey().substring(domainSchemaPreKey.length()), Map.Entry::getValue));

    m1.putAll(m3);

    LogUtils.foal(m1,"...........................");
  }
}
